# Conditional Probability

{{< include _macros.tex >}}

This is the largest section by far as the original Monty Hall problem in essence is a conditional probability problem utilizing Bayes' Rule and LOTP. All of these problems are interesting to a certain extent, but it is very understandable for readers to get tired of looking at problems involving Bayes' Rule and LOTP over and over again. Hence, we would suggest that the reader doesn't try to solve all of these problems and instead pick out ones that seem interesting to them the most. Although if you really enjoy these problems, go ahead and try to solve them all!

## Problems

2.  (Original Monty Hall). On the Monty Hall game, a contestant chooses one of three closed doors, two of which have a goat behind them and one of which has a car. Each door has equal probabilities of having the car behind it. The contestant wants to win the car. After the selection is made, Monty Hall, who knows where the car is, opens one of the two remaining doors. Monty Hall will always open a door with a goat behind it, and if he has a choice, then he picks one of the two doors at random with equal probabilities. Monty then offers the contestant the option of switching to the other unopened door. What is the probability that the contestant will win the car if they switch doors?

    ::: {#answer1 .callout-caution collapse="true"}
    ## Solution

    Without loss of generality, suppose the contestant originally chooses door 1 and Monty opens door 2. Let $C_i$ be the event that the car is behind Door $i$ and $M_i$ be the event that Monty opens Door $i$ and reveals a goat. We are looking for $P(C_3 | M_2).$ By Bayes' Rule and LOTP, this is $$ P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_2)P(C_2) + P(M_2|C_3)P(C_3)}. $$ Clearly, $P(M_2 |C_2) = 0.$ $P(M_2|C_3) = 1$ as if the contestant chooses door 1 and the car is behind door 3, Monty will always open door 2. Moreover, $P(M_2|C_1) = 1/2$ as if the car is behind door 1 and the contestant initially chooses door 1, Monty will open door 2 or door 3 with equal probabilities. Finally, $P(C_i) = 1/3$ for $i = 1, 2, 3.$ This gives us $$ P(C_3|M_2) = \frac{1/3}{(1/2)(1/3) + (1/3)} = \frac{2}{3}. $$ Therefore, the contestant should switch to have a better chance to win the car.
    :::

3.  (Reverse Monty Hall) Monty is trying a new version of his Monty Hall game. Instead of two doors containing goats and one door containing a car, there will now be two doors containing a car and one door containing a goat. The contestant initially chooses one of the three doors. Then, Monty, who knows where the car is, will open one of the two remaining doors. Monty Hall will always open a door with a $car$ behind it, and if he has a choice, he will pick one of the two doors at random with equal probabilities. Monty then offers the contestant the option of switching to the other unopened door. What is the probability that the contestant will win the car if they switch doors?

    ::: {.callout-caution collapse="true"}
    ## Solution

    This is the exact same scenario as the regular Monty Hall problem except that cars act as goats and the goat acts as the car. Hence, the probability of winning the car by switching should be equivalent to the probability of winning a goat by switching in the original problem. Thus, it is $\frac{1}{3}.$ The contestant should not switch to have a higher probability of winning the car.
    :::

1. (Lazy Monty) The original Monty Hall game is to be played, but if Monty has a choice between door 2 and door 3 and they both contain goats, Monty will choose to open door 2 with probability $p > 1/2$ as it is closer to him. All other rules of the original Monty Hall game stay the same. The contestant originally chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the contestant will win by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    The calculation stays the same as in the original Monty Hall game (See Original Monty Hall), but this time, $P(M_2|C_1) = p$ instead of $1/2$ as Monty no longer has equal probabilities to choose between door 2 and door 3 if the contestant originally chooses door 1. Hence, the probability calculation becomes
    $$
    P(C_3|M_2) = \frac{(1)(1/3)}{(p)(1/3)+(1)(1/3)} = \frac{1}{p+1}.
    $$
    Note that when $p = 1/2,$ this reduces down to $2/3,$ which makes sense. The interesting part is that if $p=1,$ the probability is $1/2$. So if Monty always prefers to open door 2 over door 3 when he can, it doesn't matter if we switch or not when Monty opens door 2. (Bonus: Does this mean that you can conclude that the probability you win the car in the $p=1$ case before the start of the game is $1/2$? Hint: You cannot.)
   :::

4.  (Any Door) Monty Hall is trying a new version of his game where after the contestant chooses a door, Monty chooses one of the two doors with the goat in it at random and opens it. Therefore, Monty can open the initial door the contestant chose if it contained a goat! If Monty opens the door that the contestant initially chose, then the contestant must choose between the two unopened doors. All other rules of the original Monty Hall game stay the same. The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the contestant will win the car by switching?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Letting $M_i$ and $C_i$ denote the usual, we have $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3)}.
    $$ First consider $P(M_2|C_3).$ If the car is behind door 3, then Monty will choose between door 1 and door 2 at random, so this probability is $1/2.$ Moreover, $P(M_2|C_1) = 1/2$ for similar reasons. Plugging these in, we find $$
    P(C_3|M_2) = \frac{(1/2)(1/3)}{(1/2)(1/3)+(1/2)(1/3)} = \frac{1}{2}.
    $$ Therefore, it doesn't matter whether the contestant switches or not; they will have a $50\%$ chance to win the car no matter what strategy they use.
    :::

5.  (Forgetful Monty) Monty Hall is about to host his show, but he has forgotten which doors hold the goats and which door holds the car. Hence, after the contestant makes their initial choice, Monty will randomly open one of the two remaining doors with equal probabilities. If Monty reveals a car, then the contestant instantly loses. If Monty reveals a goat, then the contestant is given the choice to switch or stick to their initial choice as usual. All other rules and assumptions of the original Monty Hall game apply. The contestant chooses door 1 and Monty reveals a goat behind door 2. What is the contestant's probability of winning if they switch?

    ::: {.callout-caution collapse="true"}
    ## Solution

    By Bayes' Rule and LOTP, $$
     P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3)}.
     $$ Consider $P(M_2|C_3).$ As Monty randomly chooses between door 2 and door 3, the probability that Monty opens door 2 is $1/2.$ Moreover, as the car is behind door 3, the goat must be behind door 2, so this probability is $1/2.$ Similarly, $P(M_2|C_1) = 1/2$ as it is simply the probability that Monty opens door 2. Hence, plugging this in, we have $$
     P(C_3|M_2) = \frac{(1/2)(1/3)}{(1/2)(1/3)+(1/2)(1/3)} = \frac{1}{2}.
     $$ Therefore, it does not matter whether the contestant switches or not.
    :::

1.  (Forgetful Contestant) A regular Monty Hall game is played. The contestant initially chooses a door, and Monty reveals a goat behind door 2. However, right afterwards, the contestant, who suffers from short-term memory loss, forgets what door they initially chose. Given this information, suppose the probability that the contestant initially chose door 1 is $p$ and the probability that the contestant initially chose door 3 is $1-p.$ What is the probability that the car is behind door 3?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $C_i$ and $M_i$ denote the usual so that we wish to find $P(C_3|M_2).$ Let $D_i$ be the event that the contestant initially chose door $i.$ We want to find
    $$
    P(C_3|M_2) = P(C_3|M_2,D_1)P(D_1|M_2)+P(C_3|M_2,D_3)P(D_3|M_2).
    $$
    From the regular Monty Hall problem, we know $P(C_3|M_2,D_1) = 2/3.$ Similarly, $P(C_3|M_2,D_3) = 1/3.$ Hence, we get
    $$
    P(C_3|M_2) = \frac{2}{3}p+\frac{1}{3}(1-p) = \frac{1}{3}(1+p).
    $$
    Therefore, if $p < 1/2,$ the contestant should choose door 1. If $p > 1/2,$ the contestant should choose door 3. If $p = 1/2,$ it does not matter.
    :::

1. (Somewhat Forgetful Monty) Monty has forgotten where the goats and the car are again, but unlike in the previous problem, he does remember one door that the goat is behind! However, he still does not remember where the other goat and the car are. Each goat is equally likely to be the goat that Monty remembers the location of and Monty remembering the goat's location is independent of the original arrangement of goats and the car. 

    After the contestant makes their initial choice, if the door Monty knows the goat is behind is one of the two remaining doors, Monty will open that door. However, if neither of the two doors is the door Monty knows the goat is behind (because the contestant's initial choice was that door), Monty opens one of the two remaining doors at random. If Monty reveals a car, the contestant instantly loses. If Monty reveals a goat, the contestant can choose to stick with their initial choice or switch, as usual. 
    
    The contestant initially chooses door 1 and Monty reveals a goat behind door 2. What is the probability that the contestant will win the car by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $M_i$ and $C_i$ denote the usual. Moreover, let $K_i$ be the event that Monty knows that a goat is behind door $i.$ Then, by Bayes' Rule and LOTP,
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3)}.
    $$
    We first calculate $P(M_2|C_3).$ By LOTP,
    $$
    P(M_2|C_3) = P(M_2|C_3, K_2)P(K_2 | C_3) + P(M_2|C_3, K_2^c)P(K_2^c|C_3).
    $$
    Clearly, $P(M_2|C_3, K_2) = 1$ and $P(M_2|C_3, K_2^c) = 1/2.$ Moreover, $P(K_2|C_3) = 1/2$ as if the car is behind door 3, Monty must either be remembering the location of the goat behind door 1 or the goat behind door 2 with equal probabilities. Hence, we get $P(M_2|C_3) = (1)(1/2)+(1/2)(1/2) = 3/4.$ Now we find $P(M_2|C_1).$ By LOTP,
    $$
    P(M_2|C_1) = P(M_2|C_1, K_2)P(K_2 | C_1) + P(M_2|C_1, K_2^c)P(K_2^c|C_1).
    $$
    Once again, $P(M_2|C_1, K_2) = 1.$ However, this time, $P(M_2|C_1, K_2^c) = 0$ as if the goats are hidden behind door 2 and door 3 and Monty does not know whether there is a goat behind door 2, he must know that a goat is hidden behind door 3. Thus, $P(M_2|C_1) = 1/2.$ Plugging these in,
    $$
    P(C_3|M_2) = \frac{(3/4)(1/3)}{(1/2)(1/3)+(3/4)(1/3)} = \frac{3}{5}.
    $$
    Thus, the contestant should still switch, but their probability of winning is smaller than the original Monty Hall game.
   :::

1. (Manty Holl I) Monty Hall has an identical twin named Manty Holl, and he has joined the Monty Hall game. No one can tell the difference between Monty Hall and Manty Holl In each game, Monty Hall is the host with probability $m$ and Manty Holl is the host with probability $1-m.$ The contestant is not told which of the two is hosting the show before the game begins. 

    When Monty Hall is the host, a regular Monty Hall game is played. However, when Manty Holl is the host, due to his little experience in hosting a game show, he forgets the arrangement of the prizes and hence after the contestant initially chooses a door, Manty randomly opens one of the two remaining doors with equal probabilities. If Manty Holl accidentally reveals a car, the contestant loses by default. All other rules of the Monty Hall game stay the same and the arrangement of goats and the car does not depend on who is hosting the show. 

    The contestant initially chooses door 1, and the host (who could be Monty or Manty) reveals a goat behind door 2. What is the probability the contestant would win by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $M_i$ denote the event that the host opens door $i$ and reveals a goat and $C_i$ denote the event that the car is behind door $i$ for $i = 1, 2, 3.$ We are once again looking for $P(C_3|M_2).$ Letting $R$ denote the event that Monty Hall is the host and not Manty Holl, using LOTP gives us
    $$
    P(C_3|M_2) = P(C_3|M_2, R)P(R|M_2) + P(C_3|M_2, R^c)P(R^c|M_2).
    $$
    From our previous calculations we know $P(C_3|M_2, R) = 2/3$ (See Original Monty Hall) and $P(C_3|M_2, R^c) = 1/2$ (See Forgetful Monty). Hence, we only need to find $P(R|M_2),$ which is not equal to $P(R)$. By Bayes' Rule and LOTP, we have
    $$
    P(R|M_2) = \frac{P(M_2|R)P(R)}{P(M_2|R)P(R)+P(M_2|R^c)P(R^c)}.
    $$
    We first find $P(M_2|R).$ By LOTP, we have
    $$
    P(M_2|R) = P(M_2|R, C_1)P(C_1|R) + P(M_2|R, C_3)P(C_3|R).
    $$
    Clearly, $P(C_i|R) = P(C_i)$ as where the car is does not depend on whether Monty or Manty is hosting the show. Moreover, $P(M_2|R, C_1) = 1/2$ as if Monty is the host and the car is behind door 1, Monty will randomly choose between door 2 and door 3 to open. Similarly, $P(M_2|R, C_3) = 1.$ Therefore, $P(M_2|R) = (1/2)(1/3)+(1)(1/3) = 1/2.$
    Now, we calculate $P(M_2|R^c),$ which by LOTP, is equal to
    $$
    P(M_2|R^c) = P(M_2|R^c, C_1)P(C_1|R^c) + P(M_2|R^c, C_3)P(C_3|R^c).
    $$
    We know $P(M_2|R^c, C_1) = P(M_2|R^c, C_3) = 1/2$ as if Manty is the host, he will always randomly open door 2 or door 3 with equal probabilities. Hence, $P(M_2|R^c) = (1/2)(1/3)+(1/2)(1/3) = 1/3.$ Plugging all of these in,
    $$
    P(R|M_2) = \frac{(1/2)m}{(1/2)m+(1/3)(1-m)} = \frac{3m}{m+2}.
    $$
    Hence, $\displaystyle P(R^c|M_2) = 1 - P(R|M_2) = \frac{2-2m}{m+2}.$ Finally, plugging this into our original equation gives us
    $$
    P(C_3|M_2) = (2/3)P(R|M_2) + (1/2)P(R^c|M_2) = \frac{2m}{m+2}+\frac{1-m}{m+2} = \frac{m+1}{m+2}.
    $$
    Plugging in trivial cases, if $m = 0$ (in which case Manty is always the host), the probability becomes $1/2$ as expected since if Manty is always the host, the problem reduces down to the Forgetful Monty problem (Problem 11). Moreover, if $m = 1$ (in which case Monty is always the host), the probability becomes $2/3$ as expected as if Monty is always the host, the problem reduces down to the original Monty Hall problem (Problem 1). Also, as $0 < m \leq 1$ implies that this probability is greater than $1/2,$ the contestant should always switch for all values of $m$ except $m = 0,$ in which case it does not matter.
   :::

1. (Manty Holl II) Manty Holl decides to continue his hosting career with his twin brother. This time, a contestant will play two Monty Hall games consecutively, with one hosted by Monty and the other hosted by Manty. The probability that Monty will be the first host is equal to the probability that Manty will be the first host. Assume the contestant cannot tell the two hosts apart, and that Manty still does not know where the car and goats are when he hosts. Also suppose that if Manty is the host and he accidentally reveals a car, the contestant immediately loses.

    In the first game, the contestant chooses door 1, the host reveals a goat behind door 2, and the contestant wins a car after switching to door 3. In the second game, the contestant chooses door 1, and the host reveals a goat behind door 2. What is the probability that the contestant will win by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $A$ be the event that Manty is the second host and $O$ be the event that Monty is the second host. From the last problem, we know given what happened in the first game, $P(A) = 2/3$ and $P(O) = 1/3$ as the hosts of the two games differ. Let $C_i$ and $M_i$ denote the usual for the second game. Then, we have
    $$
    P(C_3|M_2) = P(C_3|M_2,A)P(A|M_2) + P(C_3|M_2,O)P(O|M_2).
    $$
    We know $P(C_3|M_2,A) = 1/2$ and $P(C_3|M_2,O) = 2/3.$ To find $P(A|M_2),$ we use Bayes' Rule to get
    $$
    P(A|M_2) = \frac{P(M_2|A)P(A)}{P(M_2|A)P(A)+P(M_2|O)P(O)}.
    $$
    Using similar reasoning from the last problem, we get $P(M_2|A) = 1/3$ and $P(M_2|O) = 1/2.$ Hence, we get
    $$
    P(A|M_2) = \frac{(1/3)(2/3)}{(1/3)(2/3)+(1/2)(1/3)} = \frac{4}{7} \implies P(O|M_2) = \frac{3}{7}.
    $$
    Plugging these values in, we get our final answer of
    $$
    P(C_3|M_2) = (1/2)(4/7)+(2/3)(3/7) = \frac{4}{7}.
    $$
    Therefore, the contestant should still switch.
   :::

1. (Manty Holl III) This time, $n+1$ Monty Hall games will be played in a row, with either all of them being hosted by Monty or all of them being hosted by Manty with equal probabilities. The first $n$ games all go the same way: the contestant chooses door 1, the host reveals a goat behind door 2, and the contestant wins a car by switching to door 3. The final contestant initially chooses door 1, and the host reveals a goat behind door 2. What is the probability the contestant will win the car by switching to door 3? Then consider what happens when $n \to \infty$ and explain why your limit makes sense.

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $C_i$ and $M_i$ denote the usual for a single game and $O$ and $A$ also denote the usual. We have that
    $$
    P(A|C_3,M_2) = \frac{P(C_3|A,M_2)P(A|M_2)}{P(C_3|M_2)}.
    $$
    Suppose we have that $P(A) = 1-m$ (it begins at $1/2,$ but after a few updates, it will no longer be $1/2.$) we know from Manty Holl I that $P(C_3|M_2) = (m+1)/(m+2)$ and $P(A|M_2) = (2-2m)/(m+2)$. We know from Forgetful Monty, we know that $P(C_3|A,M_2) = 1/2.$ Therefore, if we had $P(A)=1-m,$ the update after one game where Monty reveals a goat behind door 2 and the contestant wins a car behind door 3 would be
    $$
    P(A|C_3,M_2) = \frac{1-m}{m+1}.
    $$

    Initially, $P(A) = 1/2.$ Finding how the value of $P(A)$ changes as the first few games are played we get $1/2,1/3,1/5,1/9,1/17,$ from which we find that the denominator is one plus a power of 2. Using induction, we can prove that this is the case (proof is omitted for space). Therefore, after $n$ games, $P(A) = 1/(2^n+1).$ Now, using the logic from Manty Holl II, we get
    $$
    P(A|M_2) = \frac{(1/3)(1/(2^n+1))}{(1/3)(1/(2^n+1))+(1/2)(2^n/(2^n+1))} = \frac{1}{1+3\cdot2^{n-1}}.
    $$
    Hence,
    $$
    P(C_3|M_2) = \frac{1}{2}\cdot \frac{1}{1+3\cdot2^{n-1}} + \frac{2}{3} \cdot \frac{3\cdot2^{n-1}}{1+3\cdot2^{n-1}} = \frac{1+2^{n+1}}{2+3\cdot2^n}.
    $$
    As $n \to \infty,$ this converges to $2/3.$ This makes sense as every time the host does not accidentally reveal a car, the more likely it is that the host is Monty Hall instead of Manty Holl, meaning the $(n+1)^{st}$ contestant is likely playing the original Monty Hall game.
   :::

6.  (For Joe) To add more variety, Monty Hall has updated the prizes on his show. There are three doors, with one prize behind each door. One door has a car behind it, one has a goat, and one has a cow, with all permutations equally likely. Monty knows what is behind each door.

    Jack, who is the contestant, will choose a door. Monty will then open a door (other than the one that Jack chose), revealing the goat or the cow. He will then let Jack choose whether to switch to the other unopened door. If Monty has a choice of which door to open, then with probability $p$ (with $0 < p \leq 1$) he will open the door with the cow.

    Unbeknownst to Monty, the cow is Jack's beloved pet, Milky White, which Jack had been forced to sell years ago. Jack doesn't want the car; his only goal is to regain Milky White.

    Jack chooses Door 1. Monty then opens Door 2, revealing the goat. If Jack decides to switch then what is the probability, given the above information, that he will regain Milky White? Should he switch?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $G_j$ and $W_j$ be the events that the goat and cow are behind Door $j$, respectively. Let $M_j$ be the event that Monty opens Door $j$. By Bayes' rule and LOTP, $$P(W_3 | M_2, G_2) = \frac{P(M_2,G_2 | W_3)P(W_3)}{P(M_2,G_2)} = \frac{P(M_2,G_2 | W_3)P(W_3)}{P(M_2,G_2|W_1)P(W_1) + P(M_2,G_2|W_3)P(W_3) },$$ since $G_2 \cap W_2$ is impossible. We have $$ P(M_2,G_2|W_3)  = P(G_2|W_3) P(M_2|G_2, W_3) =  \frac{1}{2} \cdot (1-p) = \frac{1-p}{2},$$ since if the cow is behind Door 3 then the goat is behind Door 1 or Door 2, with equal probabilities; and if the cow is behind Door 3 and the goat is behind Door 2, then Monty will open Door 3 with probability $p$. Similarly, $$P(M_2,G_2|W_1) = P(G_2|W_1) P(M_2|G_2,W_1) = \frac{1}{2} \cdot 1 = \frac{1}{2}.$$ Thus, if Jack switches to Door 3 then his probability of regaining Milky White is $$ P(W_3 | M_2, G_2) = \frac{ \frac{1-p}{2} \cdot \frac{1}{3}}{ \frac{1}{2} \cdot \frac{1}{3} + \frac{1-p}{2} \cdot \frac{1}{3}} = \frac{1-p}{2-p}.$$ So he should \emph{not} switch, since by not switching his probability of success is $$P(W_1 | M_2, G_2) = 1 - \frac{1-p}{2-p} = \frac{1}{2-p} > \frac{1-p}{2-p}.$$ As a check, note that in the case $p = 1/2$ the problem is equivalent, in terms of \nobreak information about where the car is, to the original Monty Hall problem. So the conditional \nobreak probability that Door 3 has the car is $2/3$, giving conditional probability $1/3$ that Door 3 has Milky\~White, which agrees with our above result since $(1/2)/(3/2) = 1/3$.

    As another check, note that in the extreme case $p = 1$, Door $3$ definitely has the car (else Monty would have opened Door $3$ to reveal Milky White), which agrees with our above result since $(1-1)/(2-1) = 0$.
    :::

7.  (For Joe) You are the contestant on the Monty Hall show. You get to choose one of three doors. One door has a car behind it, and the other two doors have goats behind them. All six possibilities for which entity is behind which door are equally likely. Monty knows exactly what is behind each door. Monty will open a door (other than the one you chose), revealing a goat. He will then let you choose whether to switch from your current choice to the other unopened door.

    Monty has grown fond of the two goats, and has named them Billy and Gilly. He thinks that one of the goats is more photogenic than the other. If he has a choice of which door to open, then with probability $p$ he will open the door that has Billy (where $0 \leq p \leq 1$).

    For concreteness, let your initial choice be door 1. Suppose that you decide in advance that you will switch, after Monty reveals a goat.

    (a) Find the unconditional probability that you will get the car.

    (b) Monty now opens door 2, revealing Billy. Given this information, find the probability that you will get the car.

    (c) What does your answer to (b) reduce to in the simple cases $p = 0, p = 1/2,$ and $p = 1$? Give intuitive explanations for why the answers in these three cases make sense.

    ::: {.callout-caution collapse="true"}
    ## Solution

    (a) Let $C_i, B_i, G_i$ be the events that the car, Billy, Gilly is behind door $i$, respectively. Let $M_i$ be the event that Monty opens door $i$. Let $W$ be the event that you win the car. As in the original Monty Hall problem, $$ P(W) = P(W|C_1)P(C_1) + P(W|C_2)P(C_2) + P(W|C_3)P(C_3) = 0 + \frac{1}{3} +  \frac{1}{3}  = \frac{2}{3}.$$

    (b) Given that Monty opens door 2, $W$ is equivalent to $C_3$. By Bayes' rule and LOTP,

        \begin{align*}
        P(W | M_2, B_2) &= P(C_3 | M_2, B_2)\\
        &= \frac{P(M_2,B_2 |C_3)P(C_3)}{P(M_2,B_2)} \\
        &=  \frac{P(M_2,B_2 |C_3)P(C_3)}{P(M_2,B_2 |C_1)P(C_1)+P(M_2,B_2 |C_3)P(C_3)},
        \end{align*}

        since $P(M_2,B_2|C_2) = 0$.

        If the car is behind door 3 then Billy is equally likely to be behind door 1 or door 2, and Monty will definitely open door 2. So

        $$P(M_2,B_2|C_3) = P(B_2|C_3) P(M_2|B_2,C_3) = \frac{1}{2} \cdot 1 = \frac{1}{2}.$$

        If the car is behind door 1 then Billy is equally likely to be behind door 2 or door 3, and Monty will have a choice of opening door 2 or door 3. So

        $$P(M_2,B_2|C_1) = P(B_2|C_1) P(M_2|B_2,C_1) = \frac{1}{2} \cdot p = \frac{p}{2}.$$

        Thus,

        $$P(W|M_2,B_2) = \frac{ \frac{1}{2} \cdot \frac{1}{3}}{  \frac{p}{2} \cdot \frac{1}{3} + \frac{1}{2} \cdot \frac{1}{3}} = \frac{1}{p+1}.$$

    (c) If $p = 0$ then $1/(p+1) = 1$. In this case, Monty will reveal Billy only if he is forced to. Since Monty \emph{did} reveal Billy, the car must be behind door 3 (else Monty would have opened door 3 instead, revealing Gilly). Then you'll definitely get the car by switching.

        If $p = 1/2$ then $1/(p+1) = 2/3$. Here the problem reduces to the original Monty Hall problem, for which we already knew the answer was 2/3. The two goats have different \emph{names} but not different impacts on the \emph{probabilities} in this case; observing Billy behind door 2 gives the same information about the location of the car as observing Gilly behind door 2 would have.

        If $p = 1$ then $1/(p+1) = 1/2$. In this case, if Billy is behind door 2 then Monty will definitely open door 2, so conditioning on $M_2 \cap B_2$ is equivalent to conditioning on $B_2$. Using a frequentist interpretation, imagine playing the game many times, say 12,000. We would expect each of the 6 permutations of (car, Billy, Gilly) to appear in about 2,000 games, and that Billy would be behind door 2 in about 4,000 games. Conditioning on $B_2$ says to filter down to just these 4,000 or so games. Among these games, we'd expect that for about 2,000 games the configuration is (car, Billy, Gilly) and for about 2,000 games the configuration is (Gilly, Billy, car).
    :::

1.  (Three Prizes) Rather than having one car and two goats, Monty will now play a version of his game with one car, one computer, and one goat. The three prizes will be arranged behind three doors, with one prize behind each door and with each arrangement being equally likely. Suppose the contestant prefers winning a car over winning a computer, and that they also prefer winning a computer over winning a goat.

    After the contestant makes their initial choice, Monty will open one of the two remaining doors. Monty will choose to reveal the prize the contestant prefers more with probability $p,$ and will reveal the less preferred prize with probability $1-p.$

    (a) The contestant initially chooses door 1, and Monty reveals a computer behind door 2. What is the probability that the car is behind door 3?

    (b) Repeat the problem if instead, Monty reveals a goat behind door 2.

    ::: {.callout-caution collapse="true"}
    ## Solution

    (a) Let $M_i$ denote the event of Monty revealing a computer behind door $i$ and $C_i$ denote the event of the car being behind door $i.$ We wish to find $P(C_3|M_2).$ By Bayes' Rule and LOTP, we get
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)}{P(M_2|C_3)+P(M_2|C_1)}.
    $$
    First consider $P(M_2|C_3).$ If the car is behind door 3, for Monty to reveal a computer behind door 2, the computer must first be behind door 2 with $1/2$ probability and Monty must choose to reveal it with probability $1-p.$ This gives us $P(M_2|C_3) = (1-p)/2.$ Now consider $P(M_2|C_1).$ For $M_2$ to occur given $C_1,$ we need the computer to be behind door 2 with $1/2$ probability and Monty to choose to reveal it with probability $p,$ giving us $P(M_2|C_1) = p/2.$ Plugging all of this in, we get
    $$
    P(C_3|M_2) = \frac{1-p}{1-p+p} = 1-p.
    $$

    (b) This time, let $M_i$ denote the event of Monty revealing a goat behind door $i$ and keep $C_i$ the same. We want to find
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)}{P(M_2|C_3)+P(M_2|C_1)}.
    $$
    Consider $P(M_2|C_3).$ For $M_2$ to occur given $C_3,$ the goat needs to be behind door 2 and Monty needs to choose to reveal it, giving us $P(M_2|C_3) = (1-p)/2.$ Similarly, $P(M_2|C_1) = (1-p)/2$ as well. This gives us $P(C_3|M_2) = 1/2.$
    :::

1. (Driver Goats) The original Monty Hall game is played, but the goats have become sentient and have learned how to drive! If a goat is behind a door adjacent to a door with the car, the goat will try to drive away with the car, and will succeed with probability $p.$ If it fails, nothing changes. If both goats are adjacent to the car because the car is behind door 2, the goat behind door 1 will try to drive away with the car and succeed with probability $p.$ If the goat fails, the goat behind door 3 will try to drive away with the car and succeed with probability $p.$ If the initial goat succeeded, the goat behind door 3 must stay where it is. If a goat successfully escapes with the car, then there will be nothing behind the door that contained the driver goat and the door that contained the car. The goats escaping or failing to escape with the car is independent of the initial placements of the car and goats.

    The goats' attempts to escape occur before the contestant chooses their first door, and whether the goats succeed at escaping is unknown to the contestant and Monty. After the contestant makes their initial choice, Monty will open a door that initially contained a goat as usual (but he might open an empty door if the goat escaped). 
    
    (a) The contestant chooses door 1, and Monty reveals a goat behind door 3. What is the probability that the car is behind door 2?

    (b) The contestant chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the car is behind door 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

    (a) Let $M_i$ and $C_i$ denote the usual. Let $D_i$ denote the event of the car $still$ being behind door $i$ after the goats try to escape. We want to find $P(D_2 | M_3) = P(D_2 | M_3, C_2)P(C_2|M_3).$ We first find $P(C_2|M_3).$ This is
        $$
        P(C_2|M_3) = \frac{P(M_3|C_2)P(C_2)}{P(M_3|C_2)P(C_2)+P(M_3|C_1)P(C_1)}.
        $$
        Consider $P(M_3|C_1).$ If the car is behind door 1, then the goat behind door 3 cannot escape. Therefore, if Monty decides to open door 3 with $1/2$ probability, then the goat will always be there. Thus, this probability is $1/2.$ Now consider $P(M_3|C_2).$ First, Monty has to decide to open door 3, which will always happen as Monty knows the car was initially behind door 2. Then, we need the goat behind door 3 to not escape. This can happen if the goat behind door 1 escapes with probabilty $p,$ or they both fail to escape with probability $(1-p)^2.$ Thus, this probability is $p+(1-p)^2.$ Plugging this in,
        $$
        P(C_2|M_3) = \frac{p+(1-p)^2}{p+(1-p)^2+1/2}.
        $$
        Now, we find $P(D_2|M_3,C_2).$ By Bayes' Rule with extra conditioning, this is
        $$
        P(D_2|M_3,C_2) = \frac{P(M_3|D_2,C_2)P(D_2|C_2)}{P(M_3|C_2)}.
        $$
        Consider $P(M_3|D_2,C_2).$ If the car is still behind door 2, then the goat behind door 3 did not escape. Therefore, as Monty knows the car was originally behind door 2, he will always open door 3 and reveal the goat. So this probability is 1. Now consider $P(D_2|C_2).$ The probability that the car remains behind door 2 is the probability that both goats fail to escape, which is $(1-p)^2.$ Similarly, $P(D_2^c|C_2) = 1 - (1-p)^2.$
        
        Finally, we already calculated that $P(M_3|C_2) = p + (1-p)^2.$ Therefore,
        $$
        P(D_2|M_3,C_2) = \frac{(1-p)^2}{p+(1-p)^2}.
        $$
        Thus, the solution is
        \begin{align*}
        P(D_2|M_3) &= P(D_2|M_3,C_2)P(C_2|M_3) \\
        &= \frac{(1-p)^2}{p+(1-p)^2}\cdot\frac{p+(1-p)^2}{p+(1-p)^2+1/2} \\
        &= \frac{(1-p)^2}{p+(1-p)^2+1/2}.
        \end{align*}
        If $p = 0,$ then this probability reduces down to $2/3,$ which makes sense as if the goats can never run away, this is simply a normal Monty Hall game. If $p = 1,$ then this probability is $0,$ which makes sense as if the goats are perfect at escaping, then the car will always be stolen by one of the two goats.

    (b) Don't think too hard; if there was a goat behind door 2, then no matter where the car was, that goat is the only goat that attempted to escape. Therefore, the goat being revealed behind door 2 means that it failed to escape, and hence the probability of the car being behind door 3 is the probability of the car being behind door 3 at the beginning given that Monty decided to open door 2. This is simply $2/3.$
   :::

1. (Time Travel) You are the contestant on the Monty Hall show, and you have the power to time travel. You initially chose door 1, and Monty revealed a goat behind door 2. You time travel back to right before Monty revealed the door (so that the placement of the prizes does not change), and once again, Monty reveals a goat behind door 2.

    (a) Suppose that given the initial placement of the prizes, the door Monty chooses to reveal before you time traveled is independent of the door Monty chooses to reveal after you time travel. What is the probability that the car is behind door 3?

    (b) Generalizing part (a), suppose you time traveled back $n$ times, and Monty revealed a goat behind door 2 all $n$ times. What is the probability that the car is behind door 3? Explain what happens to this probability when $n \to \infty,$ and then explain intuitively why this limit makes sense.

   ::: {.callout-caution collapse="true"}
   ## Solution

    (a) Let $C_i$ denote the usual and $B_i$ denote Monty revealing a goat behind door $i$ before you time traveled and $A_i$ denote Monty revealing a goat behind door $i$ after you time travel. We want to find $P(C_3|B_2, A_2).$ By Bayes' Rule, LOTP, and conditional independence of $B_2$ and $A_2$ given $C_3,$ we get
        $$
        P(C_3|B_2,A_2) = \frac{P(B_2|C_3)P(A_2|C_3)P(C_3)}{P(B_2|C_3)P(A_2|C_3)P(C_3)+P(B_2|C_1)P(A_2|C_1)P(C_1)}.
        $$
        We know $P(C_3) = P(C_1) = 1/3.$ Clearly, $P(B_2|C_3) = P(A_2|C_3) = 1$ and $P(B_2|C_1) = P(A_2|C_1) = 1/2.$ Thus, we get
        $$
        P(C_3|B_2, A_2) = \frac{1}{1+1/4} = \frac{4}{5}.
        $$
        Therefore, we have an even higher probability of seeing the car behind door 3 than in the original Monty Hall game, which makes sense; the more times Monty chooses to open door 2, the more likely it is that he is being forced to due to there being a car behind door 3.
    
    (b) If the car is behind door 3, then the probability of Monty revealing a goat behind door 2 all $n$ times is 1. If the car is behind door 1, then it is $1/2^n.$ Therefore, the probability is
        $$
        \frac{1}{1+1/2^n} = 1 - \frac{1}{2^n+1}.
        $$
        As $n \to \infty,$ this probability goes to 1, which makes sense as if Monty kept revealing a goat behind door 2, it is almost certain that it is because the car is behind door 3, forcing him to always pick door 2.
   :::

1. (Wizard Monty) To stop his contestants from winning a car so easily, Monty went to Hogwarts and has become a wizard. A regular Monty Hall game will be played. However, after the contestant chooses a door, if the car is behind one of the two remaining doors, Monty will cast a spell that succeeds with probability $s.$ If the spell succeeds, the goat behind the contestant's chosen door and the car switch places. If the spell fails, nothing will happen. The contestant has no way of determining whether or not Monty cast a spell and whether or not it was successful. Afterwards, Monty will open one of the remaining doors with a goat behind it. If he has a choice, he will pick between the two doors with equal probabilities. The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the contestant will win by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $M_i$ and $C_i$ denote the usual. Then,
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3)}.
    $$
    Clearly, $P(M_2|C_3)=1$ and $P(M_2|C_1) = 1/2.$ Now we calculate $P(C_1).$ Let $I_j$ be the event that the car was initially behind door $J$ and let $S$ be the event that Monty successfully cast a spell. Then, by LOTP,
    $$
    P(C_1) = P(C_1|I_1)P(I_1)+P(C_1|I_1^c, S)P(I_1^c, S) + P(C_1|I_1^c, S^c)P(I_1^c, S^c).
    $$
    We know $P(C_1|I_1^c, S^c) = 0$ and $P(C_1|I_1^c, S) = P(C_1|I_1) = 1.$ Moreover, we have $P(I_1^c, S) = P(S|I_1^c)P(I_1^c) = 2s/3.$ Therefore, $P(C_1) = (1)(1/3)+(1)(2s/3) = (2s+1)/3.$
    
    By symmetry, $P(C_2) = P(C_3).$ As $P(C_1^c) = (2-2s)/3,$ we have $P(C_3) = (1-s)/3.$ Plugging all of this in, we get
    $$
    P(C_3|M_2) = \frac{(1)(1-s)/3}{(1/2)(2s+1)/3+(1)(1-s)/3} = \frac{2-2s}{3}.
    $$
    Notice that this was also $P(C_1^c),$ which makes sense as if the car was behind door 2 or door 3 after the spell was cast, the contestant would win by switching. Plugging some values in, $s = 0$ gives us a $2/3$ chance of winning, which makes sense as the spell being guaranteed to fail turns this into a regular Monty Hall game. If $s=1,$ then the probability becomes $0,$ which makes sense as if the spell always succeeds, the contestant will never win by switching.
    
    Doing some calculations, we see that if $s > 1/4,$ the contestant should stick with their original choice to have a better chance of winning. If $s < 1/4,$ the contestant should switch. If $s = 1/4,$ it does not matter.
   :::

1. (Helpful Monty) Monty Hall has been alerted that if the contestant wins a car, he will also win a car, so now he has decided to use his wizard powers from the previous problem (Wizard Monty) to help the contestant. After the contestant makes their initial choice, if there is a car in the door the contestant initially chose, Monty will cast a spell that has probability $s$ of succeeding. 

    (a) In this part, if the spell succeeds, the car behind the door the contestant initially chose will be switched with the goat behind door 2 or door 3 with equal probabilities. If the spell fails, nothing happens. All other rules of the Monty Hall game remain the same. The contestant initially chooses door 1 and Monty reveals a goat behind door 2. What is the probability that the contestant will win by switching?

    (b) Now instead, suppose that if the spell succeeds, then the car exchanges spots with the goat whose door number is smaller than the other (i.e. if the contestant chooses door 1 and the car is behind door 1, if the spell succeeds, the car will be behind door 2 with certainty as $2 < 3$). All other rules stay the same. The contestant initially chooses door 1 and Monty reveals a goat behind door 2. What is the probability that the contestant will win by switching?

   ::: {.callout-caution collapse="true"}
   ## Solution

    (a) For this part, we will use a shortcut: If the car ends up in door 2 or door 3 after the spell (or no spell if the car was not behind door 1 in the first place), then the contestant will win by switching as Monty will open the other door. Also notice that there is nothing that makes door 2 special from door 3, so the probability that Monty opens door 2 is equal to the probability that Monty opens door 3. If the car ends up in door 1, the contestant will lose. 

        There is a $2/3$ probability that the car was initially behind door 2 or door 3. If the car was behind door 1 with $1/3$ probability, it will be moved to door 2 or door 3 with probability $s.$ Hence, the probability that the contestant will win is
        $$
        P(Win) = \frac{2+s}{3}.
        $$
        Plugging in some values, if $s = 1,$ we see that the probability of winning is $1$ as expected as Monty will always make sure the car is behind the other unopened door. If $s = 0,$ the probability reduces down to $2/3$ as expected as it becomes a regular Monty Hall game.
    
    (b) Notice that we cannot use our approach from the previous part as there is now a factor that distinguishes door 2 from door 3. Let $M_i$ and $C_i$ denote the usual. Then,
        $$
        P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3)}.
        $$
        We have $P(M_2|C_3) = 1$ and $P(M_2|C_1) = 1/2.$ We also know $P(C_3) = 1/3$ as if the car started out behind doors 1 or 2, it could not have moved to behind door 3 (because of the spell only being able to move a car from door 1 to door 2). Now, consider $P(C_1).$ The probability that the car will stay behind door 1 is if it started behind door 1 and the spell failed, which has probability $(1-s)/3.$ Thus, we get
        $$
        P(C_3|M_2) = \frac{1/3}{(1-s)/6+1/3} = \frac{2}{3-s}.
        $$
        If $s = 1$ (in which case the spell always succeeds), the probability is $1$ as expected as the goat behind door 2 indicates Monty did not cast the spell, meaning the car was not behind door 1. If $s = 0$ (in which case the spell always fails), the probability becomes $2/3$ as expected as the game reduces down to the original Monty Hall game.
   :::

1. (Santa Monty) This problem was created on Christmas! Monty Hall has decided to become Santa and is standing in a neighborhood with three houses. One person and two goats live in this neighborhood, which each house housing exactly one person or goat. Every member of the neighborhood is equally likely to be living in each house. Suppose the houses are labelled House 1, House 2, and House 3. Monty needs to find the house with the person to give them a car as a Christmas present. 

    Thankfully, Monty knows how to make a "goat call" (from all the time he spent with goats!), which will cause a goat to leave its house with probability $p.$ However, House 1 is soundproof, and hence even if a goat lives in House 1, it will never leave its house. Suppose the only way the goats will leave their house is through the ``goat call" (and the person will never leave their house). Moreover, assume that given the housing arrangement, the probabilities of the two goats exiting are independent of each another. Monty does a goat call, and a goat exits out of House 2. What is the probability that the person is at House 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $G$ be the event that a goat exits out of House 2 and nothing exits out of House 3 and let $T_i$ be the event that the person lives in House $i$. We want to find $P(T_3|G).$ By Bayes' Rule and LOTP,
    $$
    P(T_3|G) = \frac{P(G|T_3)P(T_3)}{P(G|T_3)P(T_3)+P(G|T_1)P(T_1)},
    $$
    as $P(G|T_2) = 0$ since if the person lives at House 2, a goat cannot exit out of it. We also know $P(T_3) = P(T_1) = 1/3.$ To find $P(G|T_3),$ we note that if the person is at House 3, it is guaranteed that nothing will exit House 3, and hence we simply need to find the probability that the goat will exit House 2, which is $p.$ Thus, $P(G|T_3) = p.$
    
    It remains to find $P(G|T_1).$ If goats live in both House 2 and House 3, this is the probability that the goat leaves House 2 and the other goat stays in House 3, which is $p(1-p)$ as the two events are conditionally independent. Therefore,
    $$
    P(T_3|G) = \frac{p}{p+p(1-p)} = \frac{1}{2-p}.
    $$
    Notice that this probability is always greater than $1/2$ (as we know $p \neq 0$ since a goat did exit from a goat all), so House 3 always has a higher probability of housing the person than House 1. If $p = 1,$ then this probability reduces to $1,$ which makes sense as if goats always leave from a goat call, the fact that no goat left House 3 must mean that the person lives at House 3.
   :::

1. (Monty Monty) Monty is a contestant on the Monty Hall show. Monty uses the strategy of initially picking door 1, and changing his choice after a door is revealed. Afterwards, Monty immediately brings on a contestant to play another Monty Hall game. 

    (a) If Monty won a car when he played on the show, a regular Monty Hall game will be played. However, if Monty did not win a car, all three doors will have a goat behind it. The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the contestant will win a car by switching to door 3?

    (b) Now instead suppose that if Monty lost, there will be two goats and one toy car. When Monty opens a door, he can reveal a toy car. Moreover, if he has a choice between revealing a toy car and a goat, he will choose either with equal probabilities. The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the contestant will win a car (not a toy car) by switching to door 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

   (a) Letting $W$ denote the event that Monty won his game and letting $C_i$ and $M_i$ denote the usual events, we have by LOTP
        $$
        P(C_3|M_2) = P(C_3|M_2, W)P(W | M_2) + P(C_3|M_2, W^c)P(W^c | M_2).
        $$
        Clearly, $P(C_3|M_2, W^c) = 0$ as the contestant cannot get the car if Monty did not win. Moreover, we know $P(C_3|M_2, W) = 2/3.$ Thus, we only need to find $P(W|M_2).$ By Bayes' Rule and LOTP,
        $$
        P(W|M_2) = \frac{P(M_2|W)P(W)}{P(M_2|W)P(W)+P(M_2|W^c)P(W^c)}.
        $$
        By symmetry, $P(M_2|W) = P(M_2|W^c) = 1/2.$ Moreover, $P(W) = 2/3$ from the solution to Problem 1. Hence,
        $$
        P(W|M_2) = \frac{(1/2)(2/3)}{(1/2)(2/3)+(1/2)(1/3)} = \frac{2}{3}.
        $$
        Thus, $P(C_3|M_2) = (2/3)(2/3) = 4/9.$ Another way to see this is that knowing $M_2$ doesn't give us any information about $W$; the probability of Monty opening door 2 and revealing a goat is $1/2$ regardless of if Monty won a car or not. Hence, $P(W|M_2) = P(W) = 2/3.$
    
    (b) Once again, we have
        $$
        P(C_3|M_2) = P(C_3|M_2, W)P(W | M_2) + P(C_3|M_2, W^c)P(W^c | M_2).
        $$
        We know $P(C_3|M_2, W^c)$ is still equal to zero, so we once again simply need to calculate $P(W|M_2).$ We have by Bayes' Rule and LOTP
        $$
        P(W|M_2) = \frac{P(M_2|W)P(W)}{P(M_2|W)P(W)+P(M_2|W^c)P(W^c)}.
        $$
        Once again, $P(M_2|W) = 1/2.$ However, $P(M_2|W^c) = 1/3$. This is because Monty will choose door 2 with probabilty $1/2$ and the probability that it is a goat (not a toy car) is $2/3,$ giving us the probability. Therefore, this time,
        $$
        P(W|M_2) = \frac{(1/2)(2/3)}{(1/2)(2/3)+(1/3)(1/3)} = \frac{3}{4} \implies P(C_3|M_2) = \frac{1}{2}.
        $$
        So the contestant has a slightly higher chance to win the car in this scenario compared to the scenario outlined in the previous part.
   :::

7.  (Repetitive Monty) Monty decides to change his game so that some doors may be empty. Specifically, one door is chosen with equal probabilities to hold the first goat. Afterwards, another door is chosen with equal probabilities to hold the second goat (the same door chosen before can be chosen again). Then, one of the three doors is randomly chosen with equal probabilities to hold the car. Thus, the doors that each goat and the car are hidden behind are independent of one another and a situation where a single door has both goats and the car can occur. After the contestant chooses their initial door, Monty will open a door with nothing behind it if he can. If he cannot, he will open a door with only one goat behind it if he can. If he cannot do that either, he will open a door with two goats behind it. Monty will never open a door with the car behind it. If Monty has a choice, then he chooses one of the two remaining doors with equal probabilities. All other rules of the original Monty Hall game stay the same.

    (a) The contestant chooses door 1, and Monty reveals nothing behind door 2. What is the probability that the contestant will win by switching to the other door?

    (b) What is the probability of the contestant winning by switching if Monty reveals a goat behind door 2 instead?

    ::: {.callout-caution collapse="true"}
    ## Solution

    (a) Let $M_i$ denote the event that Monty opens door $i$ and reveals nothing and $C_i$ denote the event that the car is behind door $i.$ Then, by Bayes' Rule and LOTP, $$
        P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_2)P(C_2) + P(M_2|C_3)P(C_3)}.
        $$ Again, $P(M_2|C_2) = 0.$ Moreover, $P(M_2|C_3)$ is simply the probability that no goat is behind door 2 as if the car is behind door 3, Monty must opens door 1. This probability is $(2/3)(2/3) = 4/9.$

        Now we calculate $P(M_2|C_1).$ Let $E_i$ be the event that neither goats are behind door $i.$ We have that $P(M_2|C_1) = P(M_2,E_2|C_1)$ since $M_2$ implies $E_2.$ Therefore, we have that

        $$
        P(M_2|C_1) = P(M_2|E_2,C_1)P(E_2|C_1).
        $$

        Note that $P(E_2|C_1) = \frac{4}{9}$ using logic from before. Now, the probability that Monty decides to open door 2 when there is nothing behind it depends on if there's anything behind door 3. We have using LOTP with extra conditioning that

        $$
        P(M_2|E_2,C_1) = P(M_2|E_2,C_1,E_3)P(E_3|E_2,C_1) + P(M_2|E_2^c,C_1,E_3)P(E_2^c|C_1,E_3).
        $$

        First consider $P(E_3|E_2,C_1).$ If neither goat is behind door 2, each goat is independently behind door 1 or door 3 with equal probabilities. Therefore, the probability that neither of them ends up behind door 3 is $1/4.$ Now, note that $P(M_2|E_2^c,C_1,E_3)=1$ since if door 2 has no goats and door 3 has some goats, Monty will reveal nothing behind door 2. Finally, $P(M_2|E_2,C_1,E_3) = 1/2$ since Monty has equal probabilities of revealing nothing behind door 2 or door 3 when neither door has anything behind them. Therefore,

        $$
        P(M_2|E_2,C_1) = \frac{1}{2}\cdot \frac{1}{4} + 1 \cdot \frac{3}{4} = \frac{7}{8} \implies P(M_2|C_1) =  \frac{7}{8} \cdot \frac{4}{9} = \frac{7}{18}.
        $$

        Plugging all of this back in, we find that

        $$
        P(C_3|M_2) = \frac{(4/9)(1/3)}{(4/9)(1/3)+(7/18)(1/3)} = \frac{8}{15}.
        $$

        This probability is slightly larger than $0.5,$ so the contestant should still switch.

    (b) Let $M_i$ be the event that Monty opens door $i$ and reveals exactly one goat and $C_i$ be the event that the car is behind door $i$ for $i = 1, 2, 3.$ Then, By Bayes' Rule and LOTP, $$
        P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_1)P(C_1) + P(M_2|C_2)P(C_2) + P(M_2|C_3)P(C_3)}.
        $$ Once again, $P(M_2|C_2) = 0.$ Consider $P(M_2|C_1).$ If the car is in door 1, then the only way Monty will reveal a goat behind door 2 is if both doors 2 and 3 contained a goat and Monty randomly chose door 2 (as if one of the doors did not contain a goat, Monty would have revealed nothing behind that door). The probability of this happening is the probability that goat 1 is behind door 2 or door 3 times the probability that goat 2 is behind one of the remaining doors between door 2 and door 3, which is $(2/3)(1/3) = 2/9.$ Hence, $P(M_2|C_1) = 2/9.$

        Finally, consider $P(M_2|C_3).$ If the car is behind door 3, Monty is guaranteed to open door 2, so we just need there to be a single goat behind door 2. The probability that goat 1 is behind door 2 and goat 2 is not is $(1/3)(2/3) = 2/9$ and the probability that goat 2 is behind door 2 and goat 1 is not is $(1/3)(2/3) = 2/9,$ so the probability of this is $4/9.$ Plugging these in, we find $$
        P(C_3|M_2) = \frac{(4/9)(1/3)}{(2/9)(1/3)+(4/9)(1/3)} = \frac{2}{3}.
        $$ So the contestant should switch and they have a better chance to win the car using this method than if Monty revealed nothing.
    :::

1. (Halfway Monty) To celebrate the writing of 50 out of 100 Monty Hall problems, Monty will make his game harder! The start of the game is identical to the original Monty Hall game. After the contestant makes their initial choice, Monty will only reveal \emph{half} of the prize behind one of the two remaining doors, and the contestant will be allowed to choose any one of the three doors for their final pick.

    Suppose if Monty has to choose between revealing half of a car and half of a goat, he will reveal the car with probability $c,$ and that if he has to choose between two goats, he will choose between the two with equal probabilities. Also suppose that Monty decided to do a little trolling and painted the car like a goat, so the probability that the contestant will correctly identify a prize after being shown half of it is $p \geq 1/2$ for both prizes.

    The contestant initially chooses door 1, and Monty reveals half of the prize behind door 2, which the contestant identifies as a goat. For each door, calculate the probability that the car is behind that door.

   ::: {.callout-caution collapse="true"}
   ## Solution
    Let $C_i$ be the usual and $G_2$ denote the event of Monty deciding to open door 2 and the contestant identifying the prize behind door 2 as a goat. We wish to find $P(C_i|G_2)$ for each $i.$ We begin with door 1. We have
    $$
    P(C_1|G_2) = \frac{P(G_2|C_1)P(C_1)}{P(G_2|C_1)P(C_1)+P(G_2|C_2)P(C_2)+P(G_3|C_3)P(C_3)}.
    $$
    The $P(C_i)$'s all cancel out. We first find $P(G_2|C_1).$ For this to occur, Monty must first pick door 2 with $1/2$ probability. Then, the contestant must correctly identify the goat with probability $p.$ Hence, this probability is $p/2.$ 
    
    Now, consider $P(G_2|C_2).$ If the car is behind door 2, Monty will choose door 2 with probability $c$ and the contestant will incorrectly identify it with probability $(1-p).$ So this probability is $c(1-p).$ Finally, consider $P(G_2|C_3).$ If the car is behind door 3, Monty must choose to reveal door 2 with probability $(1-c)$ and the contestant must correctly identify it with probability $p.$ So this probability is $p(1-c).$ Hence, we get
    $$
    P(C_1|G_2) = \frac{p/2}{p/2+c(1-p)+p(1-c)} = \frac{p}{3p+2c-4pc}.
    $$
    Now, we find $P(C_2|G_2).$ Just plugging in values from before, we get
    $$
    P(C_2|G_2) = \frac{c(1-p)}{p/2+c(1-p)+p(1-c)} = \frac{2c-2pc}{3p+2c-4pc}.
    $$
    And finally, we get
    $$
    P(C_3|G_2) = \frac{2p-2pc}{3p+2c-4pc}.
    $$
    If $c = 1$ and $p = 1,$ then $P(C_1|G_2) = 1$ and the other two probabilities are zero, which makes sense, because if Monty always reveals a car if he can and the contestant always identifies a prize correctly, the prize behind door 3 must be a goat (since Monty did not choose it) and the prize behind door 2 must also be a goat (since the contestant identified it as a goat), meaning the car must be behind door 1.
   :::

1. (Hidden Door) The Monty Hall game is played, and after the contestant picks door 1, Monty reveals a goat behind door 2. However, before the contestant makes his choice, Monty moves the curtain and suddenly reveals a hidden fourth door. Assume that at the start of the game, each of the four doors had the same probability of having a car, and that Monty always opens door 2 or door 3 and never door 4. If the contestant wants to maximize their chance of winning, what door should they pick, and what probability of winning do they have by doing so?

   ::: {.callout-caution collapse="true"}
   ## Solution

   We first find the probability that the car is behind door 1. By Bayes' Rule and LOTP, using the usual event notations,
    $$
    P(C_1|M_2) = \frac{P(M_2|C_1)P(C_1)}{P(M_2|C_1)P(C_1) + P(M_2|C_3)P(C_3) + P(M_2|C_4)P(C_4)}.
    $$
    We know $P(M_2|C_1) = P(M_2|C_4) = 1/2$ as Monty always reveals door 2 or door 3. Moreover, $P(M_2|C_3) = 1.$ Plugging these in,
    $$
    P(C_1|M_2) = \frac{(1/2)(1/4)}{(1/2)(1/4)+(1)(1/4)+(1/2)(1/4)} = \frac{1}{4}.
    $$
    To find $P(C_3|M_2)$ or $P(C_4|M_2),$ we simply replace the numerator with $P(M_2|C_3)P(C_3)$ or $P(M_2|C_4)P(C_4),$ respectively. Doing this, we find that choosing door 3, which gives the contestant a $1/2$ chance of winning, is the optimal choice.
   :::

1.  (Jammed Doors) A regular Monty Hall game will be played except that some of the doors may be jammed. Specifically, each door independently has a $j$ probability of being jammed. Whether a door is jammed or not is independent of whether the door contains a goat or a car. After the contestant makes their initial choice, Monty will open one of the two remaining doors that contains a goat and is not jammed, with him choosing randomly between the two if he has a choice. If neither door satisfies that constraint, then Monty will simply not do anything.

    The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the car is behind door 3?
    
    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $M_i$ and $C_i$ denote the usual and let $J_i$ be the event that door $i$ is jammed. We wish to find $P(C_3|M_2).$ (We will assume that $M_i$ implies $J_i^c,$ which makes sense.) Doing the usual Bayes' Rule and LOTP trick, we get
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)}{P(M_2|C_3)+P(M_2|C_1)}.
    $$
    We first consider $P(M_2|C_3).$ Monty nevers opens the door that contains a car, so this is simply the probability that door 2 is not jammed, $1-j.$ Now, we find $P(M_2|C_1).$ We first need door 2 to not be jammed with probability $1-j.$ Then, if door 3 is jammed, door 2 will be opened, and if door 3 is not jammed, door 2 will be opened with $1/2$ probability. This gives us
    $$
    P(C_3|M_2) = \frac{1-j}{1-j+(1-j)(j+(1-j)/2)} = \frac{2}{3+j}.
    $$
    Plugging in $j=0$ gives us the probability $2/3,$ which makes sense as if $j=0,$ the problem reduces down to the regular Monty Hall game.
    :::

1. (For Joe) Consider the following variation of the Monty Hall problem, where in some situations Monty may not open a door and give the contestant the choice of whether to switch doors. There are 3 doors, with 2 containing goats and 1 containing a car.  The car is equally likely to be anywhere, and Monty knows where the car is. Let $0 \leq g \leq 1$ and $0 \leq c \leq 1$.

    The contestant chooses a door. If this initial choice has the car, then Monty will secretly flip a coin with probability $c$ of Heads. If the coin lands Heads, Monty will open another door, revealing a goat (choosing with equal probabilities among his two choices of door), and then offer the contestant the choice of whether to switch to the other unopened door. If the coin lands Tails, Monty will not open a door, and the contestant will have to stick with their initial choice.

    If the contestant's initial choice has a goat, then Monty will secretly flip a coin with probability $g$ of Heads. If the coin lands Heads, Monty will open another door, revealing a goat, and then offer the contestant the choice of whether to switch to the other unopened door. If the coin lands Tails, Monty will not open a door, and the contestant will have to stick with their initial choice.

    The contestant decides in advance to use the following strategy: initially choose Door 1. Then, if Monty opens a door and offers the choice of whether to switch, do switch.

    (a) Find the unconditional probability that the contestant will get the car.

    (b) Check what your answer to (a) reduces to in the extreme cases where $g, c \in \{0,1\}$. Explain why your answer makes sense in each of these four extreme cases.

   ::: {.callout-caution collapse="true"}
   ## Solution

    (a) Let's define some relevant events:

        \begin{itemize}

        \item $W$: the contestant gets the car; 

        \item $C_i$: the car is behind Door $i$;

        \item $H$: Monty's coin lands Heads;

        \item $M_i$: Monty opens Door $i$ (revealing a goat).

        \end{itemize}

        By LOTP, conditioning on where the car is,

        $$P(W) = P(W|C_1)P(C_1) + P(W|C_2)P(C_2) + P(W|C_3)P(C_3).$$ By assumption, $P(C_i) = 1/3$ for $i=1,2,3$. To find $P(W|C_1)$, let's further condition on whether Monty's coin landed Heads:

        \begin{align*}
        P(W|C_1) &= P(W|C_1,H)P(H|C_1) + P(W|C_1,H^c)P(H^c|C_1)\\
        &= 0 \cdot c + 1 \cdot (1-c)\\
        &= 1-c,
        \end{align*}

        since, given $C_1$, the contestant will get the car if and only if they don't switch. Similarly, 

        \begin{align*}
        P(W|C_2) &= P(W|C_2,H)P(H|C_2) + P(W|C_2,H^c)P(H^c|C_2)\\
        &= 1 \cdot g + 0 \cdot (1-g)\\
        &= g.
        \end{align*}

        By the same calculation, with $C_3$'s in place of the $C_2$'s, we also have

        $$P(W|C_3) = g.$$ 
        
        Thus,

        $$P(W) =  \frac{1-c}{3} +  \frac{g}{3} + \frac{g}{3} = \frac{1-c+2g}{3}.$$

    (b) If $g=1,c=1,$ the answer reduces down to $2/3.$ This makes sense as this means Monty will always allow the contestant to switch, and thus we are back to the original Monty Hall problem.

        If $g=1,c=0,$ the answer reduces down to $1.$ This case means that Monty will let the contestant switch when the contestant originally chose a goat and never let them switch if they originally chose a car. In this case, the contestant does indeed always win; if they originally chose a goat, they will switch to the door that has a car, and if they originally chose a car, they will be forced to stick with their original case.

        The contrasting case is $g=0,c=1,$ which gives $0.$ This is the opposite of what happened before; now the contestant will only switch when they choose the door with the car originally, and then will switch to a door with a goat. Hence, they cannot win the car by always switching.

        Finally, if $g=0,c=0,$ the probability is $1/3.$ This makes sense as if the contestant cannot switch, the probability they win the car is simply the probability their initial pick out of 3 doors contains the car.
   :::

1.  (Language Barrier) Uh oh! Monty Hall and the contestant speak different languages, and problems may occur in the game.

    (a) The original Monty Hall game is played, except that rather than Monty revealing a goat, Monty will tell the contestant where a goat is. Specifically, after the contestant makes their initial choice, Monty will tell the contestant which of the two remaining doors contain a goat, choosing between the two with equal probabilities if he has a choice. 

        Monty will tell the contestant the door he chose in the incredible Statinese language, which the contestant is not fluent in. However, the contestant is somewhat familiar with Statinese, and will correctly understand the door Monty tells them with probability $p > 1/2,$ independent of the true arrangement of prizes. The contestant initially chooses door 1, and Monty tells the contestant his chosen door. Using their familiarity with Statinese, the contestant believes Monty said door 2. What is the probability of the car being behind each of the three doors?

    (b) Now, the contestant is only fluent in Statinese, while Monty is unable to understand Statinese. However, Monty is somewhat familiar with Statinese, so when the contestant tells Monty their initial choice, he will correctly interpret it with probability $p \geq 1/3,$ and will interpret it as one of the other two doors with probability $1-p,$ with both doors equally likely to be chosen, with this interpretation being independent of the true arrangement of prizes. Then, using his interpretation, Monty will open one of the two other doors that contains a goat with his usual rules.

        The contestant tells Monty that they initially chose door 1 in Statinese, and Monty reveals a goat behind door 2. What is the probability that the goat is behind door 3?

    ::: {.callout-caution collapse="true"}
    ## Solution

    (a) Let $C_i$ denote the usual, $M_i$ be the event of Monty telling the contestant that a goat is behind door $i,$ and $L_2$ be the event of the contestant understanding Monty's door as door 2. We wish to find $P(C_i|L_2).$ We have by Bayes' Rule
    $$
    P(C_i|L_2) = \frac{P(L_2|C_i)P(C_i)}{P(L_2|C_1)P(C_1)+P(L_2|C_2)P(C_2)+P(L_2|C_3)P(C_3)}.
    $$
    Clearly, the $P(C_i)$ terms all cancel out. Consider $P(L_2|C_1).$ By LOTP, we get
    $$
    P(L_2|C_1) = P(L_2|C_1, M_2)P(M_2|C_1) + P(L_2|C_1, M_3)P(M_3|C_1).
    $$
    We have $P(L_2|C_1, M_2) = p$ and $P(L_2|C_1, M_3) = 1-p$ from the problem statement. We also have $P(M_2|C_1) = 1/2 = P(M_3|C_1)$ as Monty randomly would choose between doors 2 and 3 with equal probabilities if the car was behind door 1. Hence, this probability is simply $1/2.$
    
        Now, consider $P(L_2|C_2),$ which by LOTP, is
        $$
        P(L_2|C_2) = P(L_2|C_2,M_2)P(M_2|C_2)+P(L_2|C_2,M_3)P(M_3|C_2).
        $$
        We know $P(M_2|C_2) = 0,$ so this probability is $P(L_2|C_2,M_3) = 1-p.$ Finally, we get
        $$
        P(L_2|C_3) = P(L_2|C_3, M_2)P(M_2|C_3) + P(L_2|C_3, M_3)P(M_3|C_3).
        $$
        We have $P(M_3|C_3) = 0,$ so this probability is $P(L_2|C_3,M_2) = p.$ Hence, we get
        $$
        P(C_1|L_2) = \frac{1/2}{1/2+p+1-p} = \frac{1}{3}.
        $$
        $$
        P(C_2|L_2) = \frac{1-p}{1/2+p+1-p} = \frac{2}{3}(1-p) < \frac{1}{3}
        $$
        $$
        P(C_3|L_2) = \frac{p}{1/2+p+1-p} = \frac{2}{3}p > \frac{1}{3}.
        $$
        Thus, the contestant should choose door 3.

    (b) Let $C_i$ and $M_i$ denote the usual ($M_i$ is Monty opening door $i$ and revealing a goat), and $D_i$ denote the event of Monty understanding the contestant's choice as door $i.$ (So $P(D_1) = p$ and $P(D_2) = P(D_3) = (1-p)/2.$) We wish to find $P(C_3|M_2).$ By Bayes' Rule and LOTP, we get
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_3)P(C_3)+P(M_2|C_1)P(C_1)}.
    $$
    We have $P(C_3) = P(C_1) = 1/3,$ so these terms cancel out. Consider $P(M_2|C_3).$ By LOTP, we get
    $$
    P(M_2|C_3) = P(M_2|C_3, D_1)P(D_1|C_3) + P(M_2|C_3, D_2)P(D_2|C_3) + P(M_2|C_3, D_3)P(D_3|C_3).
    $$
    We know $P(M_2|C_3, D_2) = 0$ as if Monty interpreted the contestant's choice as door 2, he would not open door 2. Now consider $P(M_2|C_3, D_1).$ If Monty interpreted the contestant's response as door 1 and the car is behind door 3, Monty will open door 2, so this probability is $1.$ Now consider $P(M_2|C_3, D_3).$ If Monty interpreted the contestant's choice as door 3 and the car is behind door 3, Monty will open door 2 with probability $1/2.$ Hence, we get
    $$
    P(M_2|C_3) = (1)(p) + (1/2)(1-p)/2 = \frac{1}{4}(1+3p).
    $$
    Now it remains to find $P(M_2|C_1).$ By LOTP, we get
    $$
    P(M_2|C_1) = P(M_2|C_1, D_1)P(D_1|C_1) + P(M_2|C_1, D_2)P(D_2|C_1) + P(M_2|C_1, D_3)P(D_3|C_1).
    $$
    We have $P(M_2|C_1, D_2)$ is still zero. Using similar logic as before, we get $P(M_2|C_1, D_1) = 1/2$ and $P(M_2|C_1, D_3) = 1.$ Hence, this probability is
    $$
    P(M_2|C_1) = (1/2)(p) + (1)(1-p)/2 = \frac{1}{2}.
    $$
    Plugging all of this in, we get
    $$
    P(C_3|M_2) = \frac{1/4+3p/4}{1/4+3p/4+1/2} = \frac{1+3p}{3+3p}.
    $$
    For $p \geq 1/3,$ this is always greater than or equal to $1/2,$ so the contestant should still always switch.
    :::

8.  (Random Monty) Monty is trying another version of his game where each of the three doors has a probability of $p$ to contain a car and a probability of $q=1-p$ to contain a goat independently of whether the other doors contain goats or cars. Therefore, all three doors might contain goats or all three doors might contain cars. After the contestant makes their initial choice, Monty will reveal a car out of the two remaining doors if he can and reveal a goat otherwise. If Monty can make a choice, then he will randomly choose between the two doors with equal probabilities. The contestant initially chooses door 1, and Monty reveals a car behind door 2. What is the probability that the contestant will win by switching?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Letting $M_i$ denote the event that Monty reveals a car behind door $i$ and $C_i$ denote the event that a car is behind door $i$ for $i = 1, 2, 3,$ we use Bayes' Rule and LOTP to get $$
     P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_3)P(C_3)+P(M_2|C_3^c)P(C_3^c)}.
     $$ Notice that we should not use LOTP with $C_1,$ $C_2,$ and $C_3$ as these events are no longer partitions of the event space (all of them or none of them can happen now!). We first find $P(M_2|C_3).$ Given that a car is behind door 3, Monty will only reveal a car behind door 2 if a car is behind door 2 (with probability $p$) and Monty randomly chose to open door 2 (with probability $1/2$). Hence, $P(M_2|C_3) = p/2.$

    Now we find $P(M_2|C_3^c).$ If there is a goat behind door 3, then Monty will always reveal door 2 if there is a car behind door 2. Hence, this probability is equal to the probability that a car is behind door 2, $p.$ Using the fact that $P(C_3) = p$ and $P(C_3^c) = q,$ we have $$
     P(C_3|M_2) = \frac{(p/2)(p)}{(p/2)(p)+(p)(q)} = \frac{p}{2-p}.
     $$ Plugging in some values, if $p = 1$ (in which case all three doors must contain a car), we get the probability is equal to $1$ as expected. If $p = 0$ (in which case all three doors must contain a goat), we get a probability of $0$ as expected. Also notice that as $2-p \geq 1,$ this probability is always less than or equal to $p,$ which makes intuitive sense as Monty revealing a car behind door 2 makes it more likely that there is no car behind door 3. Hence, as the probability that the contestant would win the car by sticking with their initial choice is $p,$ the contestant should never switch.
    :::

9.  (For Joe) Sonia is the contestant on the Monty Hall show. Monty plans to run the game in the standard way. The rest of this paragraph reviews the standard Monty Hall setup. There are three doors. Behind one there is a car, and behind the other two there are goats. Sonia hopes to win the car. Initially, all possibilities are equally likely for where the car is. Sonia will choose a door. Then Monty (who knows where the car is) will open a different door, revealing a goat, and offer Sonia the option of switching. If Monty has a choice of which door to open to reveal a goat, he will choose with equal probabilities.

    Sonia happens to be standing close to door 3, and not close to door 1 or door 2. She initially chooses door 1. Monty then opens door 2, revealing a goat. But just as Sonia is about to announce that she would like to switch to door 3, she hears a sound coming from behind door 3. The sound is very faint, so she is unsure what caused the sound, e.g., it could have been the bleating of a goat or the vrooming of the car.

    From a point of view of before the game started, let $b$ be the probability that Sonia will hear a sound from behind door 3, given that door 3 has a goat. Similarly, let $v$ be the probability that she will hear a sound from behind door 3, given that door 3 has the car. Assume that Monty opening door 2 is conditionally independent of Sonia hearing a sound from behind door 3, given what is behind door 3.

    Given the above information, find the probability that Sonia will get the car if she switches to door 3. Also, check what your answer reduces to in the case $b=v$ (in which case the sound is irrelevant), and discuss whether your answer makes sense in this case.

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $C_j$ be the event that door $j$ has the car, $M_j$ be the event that Monty opens door $j$, and $H_j$ be the event that Sonia hears a sound from behind door $j$. By Bayes' rule, $$ P(C_3  | M_2, H_3) = \frac{ P(M_2, H_3 | C_3) P(C_3)}{P(M_2,H_3)}.$$ For the numerator, $P(C_3) = 1/3$ and, by conditional independence, $$ P(M_2, H_3 | C_3) = P(M_2 | C_3) P(H_3 | C_3) =  v.$$ Expanding the denominator by LOTP gives $$ P(M_2,H_3|C_1) P(C_1) + P(M_2,H_3|C_2) P(C_2) + P(M_2,H_3|C_3) P(C_3)  = \frac{b}{2} \cdot \frac{1}{3} + 0 + v \cdot \frac{1}{3}.$$ Thus, $$ P(C_3 | M_2, H_3) = \frac{ \frac{v}{3}}{ \frac{b}{6} +  \frac{v}{3}} = \frac{2v}{b + 2v}.$$ If $b = v$, then this answer reduces to $2/3$, which makes sense since in this case the sound provides no information about what is behind door 3, so then the problem reduces to the classic Monty Hall problem.
    :::

1.  (Enemy Door) A normal Monty Hall game will be played, except that one of the three doors will be randomly chosen as Monty's enemy door. Each door is equally likely to be the enemy door, and the enemy door will be chosen independently from the door with the car behind it. After the contestant makes their initial choice, if the enemy door is one of the other two doors, Monty will always open it even if it contains the car. If the contestant initially chose the enemy door, then Monty will open one of the two remaining doors with his usual rules.

    The contestant initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the car is behind door 3?

    How would this change if instead, Monty never opens the enemy door even if the other remaining door contains a car?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $M_i$ and $C_i$ be the usual and let $E_i$ be the event that door $i$ is the enemy door. We wish to find $P(C_3|M_2),$ which we know (by now) is
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_3)P(C_3)+P(M_2|C_1)P(C_1)}.
    $$
    As usual, $P(C_3) = P(C_1) = 1/3$ and these cancel out. We first find $P(M_2|C_3).$ By LOTP and independence of $E_i$ from $C_i$, we get
    $$
    P(M_2|C_3) = P(M_2|C_3,E_1)P(E_1)+P(M_2|C_3,E_2)P(E_2)+P(M_2|C_3,E_3)P(E_3).
    $$
    We know $P(E_i) = 1/3.$ We have $P(M_2|C_3,E_1) = 1$ as if the enemy door is door 1, then Monty will open door 2 as door 3 has the car. Next, we get $P(M_2|C_3,E_2) = 1$ as if the enemy door is door 2, Monty must open it, and a goat will be behind it since the car is behind door 3. Finally, $P(M_2|C_3,E_3) = 0$ as if the enemy door is door 3, Monty must've opened it. Hence, we get this probability is $2/3.$
    
    Now we find $P(M_2|C_1).$ This is simply $1/2$ as if the car is behind door 1, we cannot distinguish door 2 from door 3 and hence each has an equal probability of being opened. Therefore, we get
    $$
    P(C_3|M_2) = \frac{2/3}{2/3+1/2} = \frac{4}{7}.
    $$
    With the change that Monty never opens the enemy door, the probability wouldn't change. Regardless of whether Monty always opens or never opens the enemy door, they contextually do the same thing; they force Monty to open one of the two doors over another. Therefore, the probability would remain at $4/7.$
    :::

1. (For Joe) Monty Hall, hoping to double the fun and excitement of his game, introduces a version that doubles the number of cars and the number of goats.  As usual, there are three doors. But now there are two cars and four goats, with two prizes behind each door. All possibilities for what's where are equally likely, and Monty knows what's where.

    The contestant chooses a door. Monty will then open a different door, and offer the contestant the choice of whether or not to switch to the other unopened door. If possible, Monty will open a door with two goats. If that's not possible, Monty will open a door with a car and a goat. If Monty is choosing between two doors each of which has two goats, or each of which has a car and a goat, then he chooses with equal probabilities. Suppose that the contestant decides in advance to choose Door 1 initially, and then to switch after Monty opens a door. 

    (a) Find the probability that Door 1 has both cars.

    (b)  Find the unconditional probability that the contestant will get both cars.

    (c)  Find the unconditional probability that the contestant will get at least one car. 

    (d) Monty now opens Door 2, revealing two goats. Given this information, find the probability that the contestant will get at least one car. 

   ::: {.callout-caution collapse="true"}
   ## Solution 

    (a) Imagine that behind each door there are two zones, and one car or goat is placed in each zone. Label the zones $1,2,\dots,6$ where the first two zones are behind Door 1, the next two are behind Door 2, etc. Let $C_j$ be the event that there is a car in Zone $j$. Then

        $$P(C_1,C_2) = P(C_1)P(C_2|C_1) = \frac{2}{6} \cdot \frac{1}{5} = \frac{1}{15}.$$
    
    (b) Let $A_j$ be the event that Door $j$ has both cars. The contestant will get both cars if and only if $A_2 \cup A_3$ occurs. For example, if $A_2$ occurs then Monty will open Door 3, revealing two goats, and then the contestant will switch to Door 2 and get both cars. By the same reasoning as in (a), 

        $$P(A_j) = \frac{1}{15}, \textrm{ for $j = 1,2,3$}.$$ 
        
        By disjointness,

        $$P(A_2 \cup A_3) = P(A_2) + P(A_3) = \frac{2}{15}.$$
    
    (c) If Door 1 has both cars then the contestant will not get a car. Otherwise, the contestant will get at least one car: either Door 2 and Door 3 will both have cars, or one of these two doors will have both cars. In the latter case Monty will open a door with two goats and the contestant will switch to the door with both cars. Thus, the probability is

        $$P(A_1^c) = 1 - P(A_1) = \frac{14}{15}.$$
    
    (d) Let $G_j$ be the event that Door $j$ has two goats and $M_j$ be the event that Monty opens Door $j$. Given $M_2$ and $G_2$, the contestant will get at least one car if and only if Door $1$ doesn't have both cars. So the desired probability is

        $$P(A_1^c | M_2, G_2) = 1 - P(A_1 | M_2,G_2).$$

        By Bayes' rule,

        $$P(A_1 | M_2,G_2) = \frac{  P(M_2|A_1,G_2)P(A_1|G_2)}{P(M_2|G_2)}.$$ We have

        $$P(M_2|A_1,G_2) = \frac{1}{2},$$

        since if there are two cars behind Door 1 and two goats behind Door 2, then there are two goats behind Door 3, and Monty will choose randomly between Door 2 and Door 3. Also,

        $$P(A_1|G_2) = 2 \cdot \frac{1}{4} \cdot \frac{1}{3} = \frac{1}{6},$$

        by the same reasoning as in (a) except now with 2 doors, 2 cars, and 2 goats. By LOTP,

        $$P(M_2|G_2) = P(M_2|A_1,G_2)P(A_1|G_2) + P(M_2|A_1^c,G_2)P(A_1^c|G_2) = \frac{1}{2} \cdot \frac{1}{6}  + 1 \cdot \frac{5}{6} = \frac{11}{12}.$$ 
        
        Hence,

        $$P(A_1^c | M_2, G_2)  = 1 - \frac{ \frac{1}{2} \cdot \frac{1}{6}}{\frac{11}{12}} = 1 - \frac{1}{11} = \frac{10}{11}.$$
   :::

1. (Biased Four Doors) Monty has changed his game to have four doors insted of three! Exactly one door will hold a car and all of the other doors will hold goats, with all arrangements equally likely. After the contestant picks a door, Monty will open one of the two unopened, leftmost doors that contains a goat. (Therefore, if a contestant picks door 1, Monty will first open door 2 or door 3.) As usual, if Monty has a choice, he opens one of the two doors randomly with equal probabilities. Afterwards, Monty opens one of the two remaining unopened, unpicked doors to reveal a goat, once again choosing with equal probabilities if he has a choice. 

    (a) The contestant initially picks door 1, and Monty first reveals a goat behind door 2, then reveals a goat behind door 3. What is the probability that the car is behind door 4?

    (b) This time, Monty first reveals a goat behind door 2, then reveals a goat behind door 4. What is the probability that the car is behind door 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

   (a) The reader may want to begin using Bayes and LOTP as usual, but there is no need! Think about the moment at which Monty is choosing between door 4 and 3. At this moment, since Monty can only open door 2 or door 3 at the beginning, the probability of the car being behind door 4 and door 1 are equal at $1/4.$ Now, Monty opening door 3 instead of door 4 gives you the same amount of information about door 4 as we usually get in the Original Monty Hall problem; we know that Monty chose not to open door 4! Hence, there is no reason the answer to this problem should differ from the Original Monty Hall problem, and we get that the answer is $2/3.$ (The reader is encouraged to do Bayes and LOTP to check this answer.)

   (b) Now instead of $1/4$ versus $1/4,$ we have $1/4$ probability of the car being behind door 1 versus $1/2$ for door 3 at the moment when door 2 was revealed. Reusing the equation from the Original Monty Hall problem, we get that the probability we want is
    $$
        \frac{1/2}{(1/4)(1/2)+(1/2)(1)} = \frac{4}{5}.
    $$
    This is higher than part (a); why does this make sense?
   :::

1.  (Monty Behind Doors) A variant of the Monty Hall game with four doors will be played. One of the doors will contain a car, one will contain Monty Hall, and the other two will contain a goat, with each arrangement being equally likely. The contestant will initially choose a door, and then of the remaining three doors, a door that does not have the car behind it will automatically open, with each door that does not contain the car being equally likely to be chosen to be opened. If the opened door contains Monty, he will open one of the other two remaining doors with his usual rules.

    The contestant initially chooses door 1, and Monty is revealed behind door 2. Then, Monty reveals a goat behind door 3. What is the probability that the car is behind door 4?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $M_i$ and $C_i$ be the usual, and let $H_i$ be the event that Monty Hall is revealed behind door $i.$ We wish to find $P(C_4|H_2, M_3).$ By Bayes' Rule and LOTP, we have
    $$
    P(C_4|H_2, M_3) = \frac{P(M_3|H_2, C_4)P(H_2|C_4)P(C_4)}{P(M_3,H_2|C_4)P(C_4)+P(M_3,H_2|C_1)P(C_1)}.
    $$
    We have $P(M_3|H_2,C_4) = 1$ as if the car is behind door 4, Monty must reveal the goat behind door 3. We have $P(H_2|C_4) = 1/6$ as door 2 must be chosen over door 3 with $1/2$ probability and door 2 must contain Monty with a $1/3$ conditional probability. Hence, $P(M_3,H_2|C_4) = 1/6.$
    
    Now, consider $P(M_3,H_2|C_1)=P(M_3|H_2,C_1)P(H_2|C_1).$ We have $P(M_3|H_2,C_1) = 1/2$ as Monty would open door 3 or door 4 and $P(H_2|C_1) = 1/9$ as door 2 must be chosen with $1/3$ conditional probability and Monty must be behind door 2 with another $1/3$ probability. Plugging this in, we get
    $$
    P(C_4|H_2,M_3) = \frac{1/6}{1/6+1/18} = \frac{3}{4}.
    $$
    This intuitively makes sense; the only way the car is not behind door 4 is if the contestant originally chose the door with the car, which occurs with $1/4$ probability.
    :::

1.  (Monty's Intern) Monty has gotten tired of opening doors, so he has hired an intern to do it for him! A regular Monty Hall game will be played, and after the contestant makes their initial choice, Monty will tell his intern which door to open based on his usual rules. However, the intern has a $p$ probability of hearing Monty correctly and a $1-p$ probability of mishearing Monty. If the intern mishears Monty, they will open one of the three doors at random with equal probabilities. (This includes the door the contestant initially chose) If the intern does not mishear Monty, they will open the correct door Monty told them.

    The contestant initially chooses door 1, and the intern reveals a goat behind door 2. What is the probability that the car is behind door 3?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $M_i$ now denote the event of the intern revealing a goat behind door $i,$ and let $C_i$ denote the usual. Let $T_i$ denote the event of Monty telling the intern to open door $i.$ We want to find $P(C_3|M_2).$ By Bayes' Rule and LOTP, we get
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_3)P(C_3)+P(M_2|C_1)P(C_1)}.
    $$
    Consider $P(M_2|C_3).$ In this case, Monty must've told the intern to open door 2. Then, the intern will open door 2 if they heard Monty correctly with probability $p$ or if they randomly chose door 2 with probability $1/3$ after mishearing Monty with probability $1-p.$ Hence, $P(M_2|C_3) = p+(1-p)/3 = (1+2p)/3.$
    
    Now consider $P(M_2|C_1) = P(M_2|C_1,T_2)P(T_2|C_1)+P(M_2|C_1,T_3)P(T_3|C_1).$ We know $P(T_2|C_1)=P(T_3|C_1)=1/2.$ We also know $P(M_2|C_1,T_2) = (1+2p)/3$ from our previous calculations. Finally, $P(M_2|C_1,T_3) = (1-p)/3$ as the intern must mishear Monty and randomly open door 2. Therefore, $P(M_2|C_1) = (1+2p)/6+(1-p)/6 = (2+p)/6.$ Plugging all of this in, we get
    $$
    P(C_3|M_2) = \frac{2+4p}{4+5p}
    $$
    Plugging in some values, if $p=1,$ the probability becomes $2/3,$ which makes sense as if the intern never mishears Monty, the game is now a regular Monty Hall game. If $p=0,$ the probability is $1/2,$ which also makes sense as if the intern always just opens a door randomly, them revealing a goat behind door 2 makes door 1 and door 3 equally likely to contain the car.
    :::

1.  (Monty's Intern II) Monty's intern has returned, but this time, they have more experience; once the game starts, they will know exactly where the car is located like Monty does. After the contestant makes their initial choice, Monty will still tell the intern which door to open based on his usual rules. The intern has a $p$ probability of hearing Monty correctly and a $1-p$ probability of mishearing Monty. If the intern does not mishear Monty, they open the door Monty told them. If they do mishear Monty, they will open one of the remaining two doors that does not have a car, choosing a door with equal probabilities if they have a choice. In other words, the intern would simply behave like Monty Hall.

    The contestant initially chooses door 1, and the intern reveals a goat behind door 2. What is the probability that the car is behind door 3?

    ::: {.callout-caution collapse="true"}
    ## Solution

    The reader may be tempted to use Bayes' Rule and LOTP as usual, but there is no need to do this. If the intern does not mishear Monty, then we have a regular Monty Hall game and the car is behind door 3 with $2/3$ probability. If the intern \emph{does} mishear Monty, they are still acting exactly like Monty; hence, we are still playing a regular Monty Hall game and the car is behind door 3 with $2/3$ probability. Thus, either way, the probability that the car is behind door 3 is $2/3.$ The value of $p$ does not matter.
    :::

10. (Hungry Monty) Monty Hall is planning to host the Monty Hall game as usual, but after eating exquisite goat meat for the past year, Monty has now gotten a love for goat meat and, after the goats and the car are hidden behind doors before the game, might eat the goats before the game even begins. For each goat, the probability that Monty will eat the goat before the game begins is $p$ and is independent of whether or not Monty eats the other goat and the whether each goat is eaten is also conditionally independent given which doors the goats and the car are hidden behind. Moreover, whether Monty eats a goat is also independent to the doors the goats and the car are hidden behind. Once the game starts and the contestant makes their initial choice, Monty opens a door with a goat behind it if he can and opens a door with nothing (because Monty ate the goat at that door) behind it if he cannot. Monty will still never reveal the car. If Monty has a choice, he chooses between the two remaining doors with equal probabilities.

    (a) The contestant chooses the first door and Monty reveals a goat behind the second door. What is the probability that the contestant will win the car by switching?

    (b) This time, Monty reveals nothing behind the second door. What is the probability that the contestant will win the car by switching?

    ::: {.callout-caution collapse="true"}
    ## Solution

    (a) Letting $M_i$ denote the event that Monty reveals nothing behind door $i$ and $C_i$ denote the event that the car is behind door $i$ for $i = 1, 2, 3,$ we end up with the exact same formula at the top of the solution to Problem 6 using Bayes' Rule and LOTP.

        We first consider $P(M_2|C_3).$ If the car is behind door 3, Monty must reveal door 2, so this is the probability that the goat behind door 2 was eaten, which happens with probability $p.$

        Now considering $P(M_2|C_1),$ we know for Monty to open door 2 and reveal nothing, there must have been nothing in behind both doors 2 and 3 (as if there was a goat behind door 3 and nothing behind door 2, Monty would have revealed the goat behind door 3). Moreover, after this is satisfied, Monty must have picked door 2 with $1/2$ probability. Combining this information, $P(M_2|C_1) = (1/2)p^2.$ Plugging these in, $$
        P(C_3|M_2) = \frac{(1/3)p}{(1/2)p^2(1/3)+(1/3)p} = \frac{2}{p+2}.
        $$ If $p = 1,$ the probability of winning is $2/3,$ which makes sense as the game reduces down to the original Monty Hall game except that there are two doors with nothing behind them and one door with the car behind it. Notice that this probability also decreases as $p$ increases. This makes intuitive sense because the lower $p$ is, the harder it is for Monty to open an empty door when the car is behind door 1 (which requires Monty to eat both goats with probability $p^2$) compared to opening an empty door when the car is behind door 3 (which only requires Monty to eat the goat behind door 2 with probability $p$).

    (b) Letting $M_i$ denote the event that Monty reveals nothing behind door $i$ and $C_i$ denote the event that the car is behind door $i$ for $i = 1, 2, 3,$ we end up with the exact same formula as before.

        We first consider $P(M_2|C_3).$ If the car is behind door 3, Monty must reveal door 2, so this is the probability that the goat behind door 2 was eaten, which happens with probability $p.$

        Now considering $P(M_2|C_1),$ we know for Monty to open door 2 and reveal nothing, there must have been nothing in behind both doors 2 and 3 (as if there was a goat behind door 3 and nothing behind door 2, Monty would have revealed the goat behind door 3). Moreover, after this is satisfied, Monty must have picked door 2 with $1/2$ probability. Combining this information, $P(M_2|C_1) = (1/2)p^2.$ Plugging these in, $$
        P(C_3|M_2) = \frac{(1/3)p}{(1/2)p^2(1/3)+(1/3)p} = \frac{2}{p+2}.
        $$ If $p = 1,$ the probability of winning is $2/3,$ which makes sense as the game reduces down to the original Monty Hall game except that there are two doors with nothing behind them and one door with the car behind it. Notice that this probability also decreases as $p$ increases. This makes intuitive sense because the lower $p$ is, the harder it is for Monty to open an empty door when the car is behind door 1 (which requires Monty to eat both goats with probability $p^2$) compared to opening an empty door when the car is behind door 3 (which only requires Monty to eat the goat behind door 2 with probability $p$).
    :::

11. (Very Hungry Monty) All the cars contestants have been receiving from him has made Monty very famished to the point he can even eat a car. First, a goat is hidden behind two doors and a car is hidden behind the remaining door as usual. Then, similar to the Hungry Monty game from Game 6, for each goat, Monty Hall has a probability of $g$ to eat the goat before the game begins, independent of whether the other goat was eaten. Moreover, Monty has a probability of $c$ to eat the entire car before the game begins. Monty eating a car, Monty eating each goat, and the doors the goats and the car are hidden behind are all independent events. Moreover, Monty eating a car and Monty eating each goat are also conditionally independent given which doors the goats and the car are hidden behind.

    After the contestant chooses a door, Monty will open a door with a goat behind it if he can and will open an empty door if he cannot. Monty will never reveal the car (however, if the car was eaten, then Monty is allowed to reveal the door that the car was originally behind). All other rules of the original Monty Hall game apply. The contestant first chooses door 1 and Monty reveals nothing behind door 2. What is the probability that the contestant will win the car if they switch?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $M_i$ denote the event that Monty reveals nothing behind door $i$ and $C_i$ denote the event that the car is (or was) behind door $i$ for $i = 1, 2, 3.$ Let $W$ be the event that the contestant wins and $V$ be the event that Monty eats the car. We want $P(W),$ which is equal to $P(V^c, C_3 | M_2),$ the probability that the car is behind door 3 and the car has not been eaten yet. By Bayes' Rule and LOTP, $$
     P(V^c, C_3|M_2) = \frac{P(M_2|V^c, C_3)P(V^c, C_3)}{P(M_2|C_1)P(C_1)+P(M_2|C_2)P(C_2)+P(M_2|C_3)P(C_3)}.
     $$

    Note that $P(M_2|C_2) \neq 0$ because Monty could have eaten the car behind door 2. As $V^c$ and $C_3$ are independent events, we have $P(V^c, C_3) = P(V^c)P(C_3) = (1-c)/3.$ Now we examine $P(M_2|V^c, C_3).$ If the car is behind door 3 and the car has not been eaten yet, Monty must reveal door 2. Hence, the probability that Monty will reveal a goat behind door 2 in this case is simply the probability that the goat behind door 2 is eaten, which occurs with probability $g.$

    Now we look at $P(M_2|C_1).$ In this case, Monty must have opened door 2 because both goats have been eaten and Monty randomly chose to open door 2. This happens with probability $g^2/2.$ Now consider $P(M_2|C_2).$ For this to happen, Monty must have eaten the car behind door 2 and the goat behind door 3 and randomly chose to open door 2. This happens with probability $gc/2.$

    We finally look at $P(M_2|C_3).$ By LOTP, $$P(M_2|C_3) = P(M_2|C_3, V)P(V|C_3) + P(M_2|C_3, V^c)P(V^c|C_3).$$ As Monty eating the car does not depend on what door the car is behind, $P(V|C_3) = c$ and $P(V^c|C_3) = 1-c.$ Moreover, we already found $P(M_2|C_3, V^c) = g.$ Hence, we only need to find $P(M_2|C_3, V).$ In this case, Monty must eat the goat behind door 2 and choose to open door 2 (because door 3 is also empty). This happens with probability $g/2.$ Plugging all of these in, \begin{align*}
     P(V, C_3|M_2) &= \frac{g(1-c)/3}{(g^2/2)(1/3)+(gc/2)(1/3)+(g/2)(c)(1/3)+(g)(1-c)(1/3)}\\
     &= \frac{2(1-c)}{g+2}.
     \end{align*}
    :::

1.  (Parallel Universe) Monty Hall has decided to host his game in two parallel universes at the same time! In both universes, a regular Monty Hall game will be played, and the arrangement of prizes in the two universes will be the same (If door 3 contains the car in universe 1, it also does in universe 2). The contestants in the two universes differ, and will initially choose one of the three doors randomly with equal probabilities. Afterwards, of the door(s) that \emph{neither} contestants chose (of which there could be two or one depending on if the two contestants chose the same door or not), Monty will open a door with a goat if he can, with him choosing randomly with equal probabilities between doors if he has a choice. The door that Monty chooses to open in this case would be the same in both universes. However, if there is only one door that neither contestants chose and that door contains the car, Monty will choose one of the three doors randomly and open it in both universes (with him opening the same door in both universes).

    The contestant in the first parallel universe initially chooses door 1, and Monty reveals a goat behind door 2. What is the probability that the car is behind door 3?

    ::: {.callout-caution collapse="true"}
    ## Solution

    Let $C_i$ and $M_i$ denote the usual, and let $D_i$ be the event that the contestant in the second parallel universe initially chose door $i.$ We wish to find $P(C_3|M_2).$ By Bayes' Rule and LOTP, we get
    $$
    P(C_3|M_2) = \frac{P(M_2|C_3)P(C_3)}{P(M_2|C_3)P(C_3)+P(M_2|C_1)P(C_1)}.
    $$
    We first find $P(M_2|C_3).$ By LOTP, we get
    $$
    P(M_2|C_3) = \frac{1}{3}(P(M_2|C_3, D_1)+P(M_2|C_3,D_2)+P(M_2|C_3,D_3)).
    $$
    We have $P(M_2|C_3,D_1) = 1$ as if the car is behind door 3 and both contestants chose door 1, Monty must open door 2 in both universes. Similarly, $P(M_2|C_3,D_3) = 1.$ We have $P(M_2|C_3,D_2) = 1/3$ as if the car is behind door 3 and the contestants chose door 1 and door 2, Monty needs to randomly choose door 2 with $1/3$ probability for $M_2$ to occur. Hence, we get $P(M_2|C_3) = 7/9.$
    
    Now, we find $P(M_2|C_1).$ By LOTP, we get
    $$
    P(M_2|C_1) = \frac{1}{3}(P(M_2|C_1,D_1)+P(M_2|C_1,D_2)+P(M_2|C_1,D_3)).
    $$
    Using similar reasoning, we get $P(M_2|C_1,D_1) = 1/2,$ $P(M_2|C_1, D_2) = 0,$ and $P(M_2|C_1,D_3) = 1.$ This gives us $P(M_2|C_1) = 1/2.$ Plugging it all in, we get
    $$
    P(C_3|M_2) = \frac{7/9}{7/9+1/2} = \frac{14}{23}.
    $$
    :::

1. (Maximum Monty) Monty Hall has $n$ doors. Exactly $c$ cars will be hidden, where $c$ is an integer between 1 and $n,$ inclusive, with each integer being equally likely to be picked. After $c$ is chosen, the cars will be randomly hidden behind $c$ different doors, with each door equally likely to be picked, and the remaining doors will hold goats. A contestant on this show will, on each turn, either ask Monty to open a door or ask to end the game. If the contestant asks Monty to open a door, Monty will open a door with a goat if one remains; otherwise, Monty will use his wizard powers to turn one random car into a goat (without the contestant noticing) and open the door containing the new goat. The contestant cannot tell the difference between a goat and a goat that used to be a car. Afterwards, the contestant must choose between asking Monty to open another door and ending the game.

    If the contestant asks for the game to end, Monty will reveal the prizes behind all of the remaining doors. If even $one$ of the unopened doors contains a goat, the contestant walks away with nothing. Otherwise, the contestant will win all of the cars that remain. A contestant wants to maximize the expected number of cars they will win. What strategy should they use, and what is the expected number of cars they will win by using it?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $G$ be the number of goats originally in the game. Let $X_k$ be the number of cars the contestant will win if they ask for the game to end after $k$ turns. We have $X_k = 0$ if $k < G$ and $X_k = n - k$ if $k \geq G.$ Therefore, we have
    $$
    E(X_k) = (n-k)P(G \leq k) = \frac{(n-k)(k+1)}{n},
    $$
    where we assume $k < n$ (as there is at least one car, there is no reason the contestant should ask Monty to open another door when all but one door have been opened). We can rewrite this as
    $$
    E(X_k) = -\frac{1}{n}k^2+\frac{n-1}{n}k+1,
    $$
    which is a downward sloping parabola, meaning it achieves its maximum value at its vertex. The coordinate of the vertex is $-((n-1)/n)/(-2/n) = (n-1)/2.$ Therefore, if $n$ is odd, we should set $k = (n-1)/2$ to maximize the expected number of cars won. Otherwise, by symmetry of the parabola, we can either have $k = n/2$ or $(n-2)/2$ to maximize the expected value.
    
    If $n$ is odd, we have
    $$
    E(X_{(n-1)/2}) = \frac{(n+1)^2}{4n}.
    $$
    If $n$ is even, we have
    $$
    E(X_{n/2}) = \frac{n+2}{4} = E(X_{(n-2)/2}).
    $$
   :::

1. (Goats and Horses) A variant of the Monty Hall game is played. There are three doors as usual, and a door is first picked with equal probabilities to hold the car. Then, the other two doors will independently have either a goat or a horse behind it. The probability of a goat being hidden is $g$ and the probability of a horse being hidden is $1-g.$

    Monty has a goat whistle, which only goats can hear, and a horse whistle, which only horses can hear. The contestant cannot tell the difference between the two whistles, but Monty can. If the contestant first picks a door with a goat, Monty will blow the horse whistle. If the contestant first picks a door with a horse, Monty will blow the goat whistle. If the contestant first picks the door with the car, Monty will either blow the goat whistle or the horse whistle with equal probabilities, independent of what prizes are in the other doors.

    When a whistle is blown, each corresponding animal will exit their door with probability $p$ and stay behind the door with probability $1-p,$ independent of all the other animals and the arrangement of the prizes. Of course, because of how Monty chooses which whistle to blow, an animal will never exit the door the contestant initially picked.

    The contestant initially picks door 1, and Monty blows a whistle, causing a goat to exit door 2 (of course, this means Monty blew the goat whistle). What is the probability that the car is behind door 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

    Let $W_g$ be the event of Monty blowing the goat whistle. Let $G_i, H_i,$ and $C_i$ denote the event of a goat, horse, and car being hidden behind door $i,$ respectively. Let $E_i$ denote the event of a goat escaping door $i$ after the whistle is blown. We wish to find $P(C_3|E_2,E_3^c).$

    By Bayes' Rule and LOTP, we have $$
     P(C_3|E_2,E_3^c) = \frac{P(E_2,E_3^c|C_3)P(C_3)}{P(E_2,E_3^c|C_3)P(C_3)+P(E_2,E_3^c|C_1)P(C_1)}.
     $$ As usual, $P(C_3) = P(C_1) = 1/3,$ so those terms cancel out. Consider $P(E_2,E_3^c|C_3).$ If the car is hidden behind door 3, we know a goat will never escape door 3. Then, for the goat to escape door 2, we need door 1 to hold a horse (otherwise Monty would've blown the horse whistle) and door 2 to hold the goat, then have the goat escape once the whistle is blown. The arrangement has a $1/4$ probability of occurring, and the goat will escape with probability $p,$ so by independence, this probability is $p/4.$

    Now consider $P(E_2,E_3^c|C_1).$ By LOTP, we have this is equal to $$
     P(E_2,E_3^c|C_1,G_3,W_g)P(G_3|C_1,W_g)P(W_g|C_1)+P(E_2,E_3^c|C_1,H_3,W_g)P(H_3|C_1,W_g)P(W_g|C_1).
     $$ Consider $P(E_2,E_3^c|C_1,G_3,W_g).$ We first need door 2 to hold a goat with probability $g,$ and then after the whistle is blown, that goat needs to escape with probability $p,$ and the goat behind door 3 needs to stay put with probability $1-p.$ Thus, this probability is $gp(1-p).$ Similarly, for $P(E_2,E_3^c|C_1,H_3,W_g),$ we need to have a goat to be behind door 2 with probability $g,$ then escape with probability $p,$ giving us a probability of $gp.$ (Notice that as a horse is behind door 3 and the goat whistle is blown, it will not escape.)

    Given $C_1,$ we know the whistle Monty blows and the prizes in the other doors are independent. Thus, $P(G_3|C_1,W_g) = P(G_3|C_1) = g.$ For the same reason, $P(H_3|C_1,W_g) = 1-g.$ Finally, we know if the car is behind door 1, Monty will pick the goat whistle or horse whistle with equal probabilities, so $P(W_g|C_1) = 1/2.$ Combining all this together, we get $$
     P(E_2,E_3^c|C_1) = \frac{1}{2}(g^2p(1-p)+gp(1-g)) = \frac{gp}{2}(1-gp).
     $$ Thus, our final answer is $$
     P(C_3|E_2,E_3^c) = \frac{p/4}{p/4+gp(1-gp)/2} = \frac{p}{p+2gp(1-gp)}.
     $$
   :::


1. (Goat Breakout) A regular Monty Hall game is played, and the contestant initially chooses door 1. Before Monty reveals a door however, a goat destroys door 2 and runs away. "Well, I guess the goat did the revealing for me! Would you like to switch, or stick with your initial choice?" Monty announces.

    Suppose that each goat independently (and conditionally independently on the placement of the prizes) has an $m$ probability of destroying its door and escaping before Monty reveals a door. What is the probability that the contestant will win the car by switching to door 3?

   ::: {.callout-caution collapse="true"}
   ## Solution

   Let $C_i$ denote the usual and $G_i$ denote the event of a goat behind door $i$ destroying its door. We wish to find $P(C_3|G_2,G_1^c,G_3^c).$ By Bayes' Rule and LOTP, we have
    $$
    P(C_3|G_2,G_1^c,G_3^c) = \frac{P(G_2,G_1^c,G_3^c|C_3)P(C_3)}{P(G_2,G_1^c,G_3^c|C_3)P(C_3)+P(G_2,G_1^c,G_3^c|C_1)P(C_1)}.
    $$
    We know if $C_i$ happens, then $G_i$ cannot happen as there is no goat behind door $i.$ Therefore, $P(G_2,G_1^c,G_3^c|C_3) = P(G_2,G_1^c|C_3) = m(1-m)$ by conditional independence and $P(G_2,G_1^c,G_3^c|C_1) = P(G_2,G_3^c|C_1) = m(1-m)$ for the same reason. Thus, those two probabilities are equal and plugging those in yields a final answer of $1/2.$ Therefore, the fact that the goat revealed itself just decreased the probability of the contestant winning from $2/3$ to $1/2.$
    
    Side Note: If we are guaranteed that door 1 is goatproof and thus if a goat is behind door 1, it cannot escape, then we get a rephrased version of Santa Monty!
   :::
